// verify_simple_certificates.m -- endomorphism-side certificates for the
// geometrically simple census (Table 1, tab:census) of the paper, and
// for the [2,22] subsection.
// The certified curves are read from table1.txt (the machine-readable
// table data from which table1.tex is typeset); run from this directory:
//   magma -b verify_simple_certificates.m
//
// Part A (every displayed curve): a good-prime Frobenius ROOT-POWER
//   certificate of geometric simplicity: an admissible prime p (good
//   reduction) whose Frobenius characteristic polynomial chi_p is
//   irreducible with Degree(MinimalPolynomial(pi^n)) = 4 for all n in
//   [2..12].  One such prime certifies that Jac(C) is geometrically simple
//   (Leprevost root-power criterion; a geometrically split or CM surface
//   would exhibit a degree drop for some power of Frobenius at every good
//   prime).
// Part B (every non-RM row): an End(Jac_Qbar) = Z certificate.  The
//   primary route is Zywina's two-Frobenius-polynomial criterion
//   [Zywina, "Determining monodromy groups of abelian varieties",
//   Res. Number Theory 2022, SS 1.5-1.6 and the unconditional pattern of
//   SS 1.8]: find good ORDINARY primes q and p (ordinary <=> p does not
//   divide the middle coefficient of chi_p, which removes his Conjecture
//   4.5 by Noot) such that
//     (a) Phi_q, the subgroup of Qbar^* generated by the roots of chi_q,
//         is free of rank 3 -- then the Frobenius torus T_q is a maximal
//         torus of the ell-adic monodromy group, and by Larsen--Pink
//         (Thm 4.3 of [LP95]) the Mumford--Tate conjecture holds for A,
//         with rank MT(A) = 3;
//     (b) Phi_p is free of rank 3, [Q(W_p) : Q] = 8, and Q(W_p) is
//         linearly disjoint from L := Q(W_q) (checked as
//         deg SplittingField(chi_q * chi_p) = 8 * deg L); then
//         Gal(L(W_p)/L), of order 8, embeds into the Weyl group of MT(A),
//         so |W(MT(A))| = 8.
//   A connected reductive rank-3 subgroup of GSp_4 with Weyl group of
//   order 8 must contain the full C_2 root system, hence equals GSp_4.
//   So MT(A) = GSp_4, which gives End(Jac_Qbar) = Z AND (independently of
//   Part A) geometric simplicity.  Freeness of Phi is certified exactly:
//   the valuation vectors of the four roots at the primes above p span a
//   rank-3 lattice, and the generator of the rank-1 kernel evaluates to 1
//   (a relation with zero valuations everywhere and unit archimedean
//   absolute values is a root of unity, by the product formula).
//   Two fallback routes (used only if the search above fails):
//   (i) Conductor route (database rows): an ODD prime p with
//       ord_p(N) = 1.  Since f_p = 2u + t + delta, exponent 1 forces
//       semistable reduction at p with toric rank t = 1 [SGA 7], which
//       persists over every extension; End^0(Jac_Qbar) then acts unitally
//       on X_*(T) tensor Q = Q, and a unital homomorphism from a division
//       algebra to Q forces End^0 = Q.  Geometric simplicity (Part A) is
//       essential here: a product E1 x E2 also admits such a homomorphism
//       (projection), and split Jacobians with exponent-1 primes exist --
//       e.g. the split [2,2,4,4] witness of Table 2 has ord_11(N) = 1.
//       Odd primes only: Magma's conductor exponent at 2 can be heuristic
//       (Ogg warning); odd exponents are rigorous (Ogg--Saito/Liu).
//   (ii) Torsion route (the new curves, whose discriminants are too large
//       to factor for a conductor computation, and any row without an odd
//       exponent-1 prime): a second strict prime whose splitting field is
//       linearly disjoint from the first (so the center of the geometric
//       endomorphism algebra is Q, excluding RM and CM; cf.
//       Costa-Lombardo-Voight 2021, Zywina 2022), plus #tors > 18,
//       excluding quaternionic multiplication
//       (Laga-Schembri-Shnidman-Voight 2024).
// Part C (the RM rows [31] and [2,22], flag 2): the simplicity certificate
//   of Part A, plus a rigorous UPPER bound End^0(Jac_Qbar) in
//   {Q, Q(sqrt 2)} resp. {Q, Q(sqrt 5)}: two strict primes whose quartic
//   Frobenius fields are non-isomorphic with Galois closure of degree 8
//   bound the center of End^0 inside their unique (real) quadratic
//   subfield or Q (Costa--Lombardo--Voight), excluding quartic CM and
//   imaginary quadratic multiplication, while #tors > 18 excludes
//   quaternionic multiplication (Laga--Schembri--Shnidman--Voight 2024) --
//   so the algebra is Q or exactly the claimed real quadratic field.  The
//   remaining LOWER bound (the RM endomorphism exists) is not certifiable
//   from L-polynomials (finitely many Frobenius data never prove an
//   endomorphism exists; cf. Zywina, Remark 1.14(ii) and the conditional,
//   almost-all nature of his Theorems 1.1/1.12) and is cited, supported by
//   real-multiplication EVIDENCE: at every admissible prime
//   p < 200 with chi_p irreducible, the real quadratic field
//   Q(pi + p/pi) = Q(sqrt(a_p^2 - 4 b_p + 8p)) has constant squarefree
//   discriminant core (2 for [31], 5 for [2,22]).  The identification of
//   the RM field is cited (for [31]: the curve is attached to the newform
//   1830.2.a.q of the modular-abelian-surfaces dataset; for [2,22]: the
//   extended-database endomorphism data).
// Part D (the [2,22] subsection): for BOTH displayed curves: exact torsion
//   [2,22]; exactly two rational Weierstrass points W1, W2; a rational
//   point P with [P - W_i] of order 22 for both i; and the RM evidence.

SetColumns(0);
SetMemoryLimit(8*10^9);
Q := Rationals(); Z := Integers();
R<x> := PolynomialRing(Q);
Tp<T> := PolynomialRing(Q);

// integral model of y^2 = 4f + h^2 (even Weierstrass form of y^2 + hy = f)
function IntSextic(f, h)
    g := 4*f + h^2;
    d := LCM([Z | Denominator(c) : c in Coefficients(g)]);
    return R!(d^2*g);
end function;

// Frobenius characteristic polynomial of Jac(y^2 = g) at p, or 0 if p is
// not admissible (bad reduction of the given model)
function ChiAt(g, D, p)
    if p eq 2 or D mod p eq 0 then return Tp!0; end if;
    if (Z!LeadingCoefficient(g)) mod p eq 0 then return Tp!0; end if;
    gp := PolynomialRing(GF(p))!g;
    if Degree(gp) lt 5 or not IsSquarefree(gp) then return Tp!0; end if;
    return Tp!Reverse(Coefficients(
        EulerFactor(Jacobian(HyperellipticCurve(gp)))));
end function;

// root-power strictness of chi (no degree drop of pi^n for n <= 12)
function IsStrict(chi)
    if Degree(chi) ne 4 or not IsIrreducible(chi) then return false; end if;
    K := NumberField(chi); pi := K.1;
    for n in [2..12] do
        if Degree(MinimalPolynomial(pi^n)) lt 4 then return false; end if;
    end for;
    return true;
end function;

function StrictPrime(g, D, pmax)
    for p in PrimesInInterval(3, pmax) do
        chi := ChiAt(g, D, p);
        if chi ne 0 and IsStrict(chi) then return p, chi; end if;
    end for;
    return 0, Tp!0;
end function;

// second strict prime with splitting field linearly disjoint from chi0's
function DisjointPrime(g, D, p0, chi0, pmax)
    d0 := Degree(SplittingField(chi0));
    for p in PrimesInInterval(3, pmax) do
        if p eq p0 then continue; end if;
        chi := ChiAt(g, D, p);
        if chi eq 0 or not IsStrict(chi) then continue; end if;
        if Degree(SplittingField(chi0*chi))
                eq d0*Degree(SplittingField(chi)) then
            return p, chi;
        end if;
    end for;
    return 0, Tp!0;
end function;

// Phi_p (the subgroup of Qbar^* generated by the roots of chi) is free of
// rank 3: the valuation vectors of the roots at the primes above p span a
// rank-3 lattice and the rank-1 kernel generator evaluates to exactly 1
function PhiFreeRank3(chi, p)
    K := SplittingField(chi);
    rts := [ r[1] : r in Roots(PolynomialRing(K)!chi) ];
    if #rts ne 4 then return false; end if;
    P := [ d[1] : d in Decomposition(MaximalOrder(K), p) ];
    M := Matrix(Z, 4, #P,
        [ Valuation(rts[i], P[j]) : j in [1..#P], i in [1..4] ]);
    if Rank(M) ne 3 then return false; end if;
    a := Eltseq(KernelMatrix(M)[1]);
    return &*[ rts[i]^a[i] : i in [1..4] ] eq K!1;
end function;

// Zywina's two-polynomial GSp_4 certificate (see the header): returns
// ordinary good primes q, p with Phi free of rank 3 at both,
// deg Q(W_p) = 8, and Q(W_p) linearly disjoint from Q(W_q)
function ZywinaGSp4(g, D, pmax)
    cand := [];                      // < p, chi, deg splitting field >
    for p in PrimesInInterval(3, pmax) do
        chi := ChiAt(g, D, p);
        if chi eq 0 then continue; end if;
        if (Z!Coefficient(chi, 2)) mod p eq 0 then continue; end if;  // ordinary
        if not PhiFreeRank3(chi, p) then continue; end if;
        ds := Degree(SplittingField(chi));
        // try the new candidate against the earlier ones (p-role needs ds = 8)
        for e in cand do
            if ds eq 8 and Degree(SplittingField(e[2]*chi)) eq 8*e[3] then
                return true, e[1], p;                 // q = e[1], p
            end if;
            if e[3] eq 8 and Degree(SplittingField(chi*e[2])) eq 8*ds then
                return true, p, e[1];                 // q = p, p = e[1]
            end if;
        end for;
        Append(~cand, <p, chi, ds>);
    end for;
    return false, 0, 0;
end function;

// squarefree core of a_p^2 - 4 b_p + 8p = disc of the min poly of
// alpha = pi + p/pi; 0 when that quantity is a perfect square (alpha in Q)
function RMCore(chi, p)
    a := -Coefficient(chi, 3); b := Coefficient(chi, 2);
    d := Z!(a^2 - 4*b + 8*p);
    if d le 0 or IsSquare(d) then return 0; end if;
    s, _ := SquarefreeFactorization(d);
    return s;
end function;

procedure RMEvidence(g, D, target, ~nontrivial)
    cores := {};
    nontrivial := 0;
    for p in PrimesInInterval(3, 200) do
        chi := ChiAt(g, D, p);
        if chi eq 0 or not IsIrreducible(chi) then continue; end if;
        c := RMCore(chi, p);
        if c ne 0 then Include(~cores, c); nontrivial +:= 1; end if;
    end for;
    assert cores eq { target };
end procedure;

// The certified curves ARE the displayed table rows: read them from
// table1.txt (the machine-readable table data from which table1.tex is
// typeset by make_tables.py), so certificate and table cannot drift.
// Per-row routing is derived from the same data: rows whose Source
// column carries the RM flag get the Part C treatment (fl = 2),
// non-database rows (label "-") use the torsion fallback (fl = 1),
// database rows the conductor fallback (fl = 0).  The tag printed with
// each certificate is the curve itself, [[f],[h]] coefficient lists.
rows := [* *];
for line in Split(Read("table1.txt"), "\n") do
    if #line eq 0 or line[1] eq "#" then continue; end if;
    parts := Split(line, "|");
    assert #parts eq 7;   // group | [[f],[h]] | label | display | source | route | comment
    fh := eval parts[2];
    fl := Position(parts[5], "RM") ne 0 select 2 else
          (parts[3] eq "-" select 1 else 0);
    Append(~rows, <eval parts[1], fh[1], fh[2], fl, parts[2]>);
end for;
assert #rows eq 73 and #[ i : i in [1..#rows] | rows[i][4] eq 2 ] eq 2;



t0 := Cputime();
nsimple := 0; nendz := 0;
for row in rows do
    I, fc, hc, fl, tag := Explode(row);
    g := IntSextic(R!fc, R!hc);
    D := Z!Discriminant(g);
    p0, chi0 := StrictPrime(g, D, 500);
    assert p0 ne 0;
    printf "SIMPLE  %-14o p=%-3o chi=%o  (%o)\n", I, p0, chi0, tag;
    nsimple +:= 1;
    if fl eq 0 or fl eq 1 then
        // primary: Zywina's two-polynomial GSp_4 certificate
        okz, qz, pz := ZywinaGSp4(g, D, 500);
        if okz then
            printf "END=Z   %-14o GSp4 monodromy: q=%o, p=%o ordinary, Phi free rank 3, [L(W_p):L]=8\n",
                I, qz, pz;
            nendz +:= 1;
        elif fl eq 0 then
            // fallback (i): an odd conductor-exponent-1 prime
            N := Conductor(ReducedMinimalWeierstrassModel(HyperellipticCurve(g)));
            oddexp1 := [ w[1] : w in Factorization(N) | w[2] eq 1 and w[1] ne 2 ];
            assert #oddexp1 gt 0;
            printf "END=Z   %-14o N=%o, ord_%o(N)=1: semistable toric rank 1 + simplicity\n",
                I, N, oddexp1[1];
            nendz +:= 1;
        else
            // fallback (ii): disjoint splitting fields + #tors > 18
            q0, chiq := DisjointPrime(g, D, p0, chi0, 500);
            assert q0 ne 0 and &*I gt 18;
            printf "END=Z   %-14o q=%-3o chi=%o  [disjoint splitting fields; #tors=%o>18]\n",
                I, q0, chiq, &*I;
            nendz +:= 1;
        end if;
    elif fl eq 2 then
        target := I eq [31] select 2 else 5;
        // upper bound End^0 in {Q, Q(sqrt target)}: two root-power-strict
        // primes whose quartic Frobenius fields have Galois closure of
        // degree 8 (hence a UNIQUE quadratic subfield, the real field
        // Q(pi + p/pi) = Q(sqrt target)) and are non-isomorphic.  By
        // Costa--Lombardo--Voight the center of End^0(Jac_Qbar) embeds in
        // each such Q(pi_p), so it lies in {Q, Q(sqrt target)}: quartic CM
        // and imaginary quadratic multiplication are excluded.  #tors > 18
        // excludes quaternionic multiplication (LSSV 2024).  Since the only
        // remaining Albert types for a geometrically simple surface are
        // End^0 = Q and End^0 = a real quadratic field, this proves
        // End^0 in {Q, Q(sqrt target)}.  The lower bound (End^0 <> Q,
        // i.e. the RM endomorphism EXISTS) cannot be certified from
        // L-polynomials -- finitely many Frobenius data never prove an
        // endomorphism exists -- and is cited, with the constant
        // discriminant-core evidence printed below.
        flds := [];
        for p in PrimesInInterval(3, 500) do
            chi := ChiAt(g, D, p);
            if chi eq 0 or not IsStrict(chi) then continue; end if;
            if Degree(SplittingField(chi)) ne 8 then continue; end if;
            if RMCore(chi, p) ne target then continue; end if;
            K := NumberField(chi);
            if #flds eq 0 then
                Append(~flds, <p, K>);
            elif not IsIsomorphic(flds[1][2], K) then
                Append(~flds, <p, K>); break;
            end if;
        end for;
        assert #flds eq 2 and &*I gt 18;
        printf "ENDBOUND %-13o End^0 in {Q, Q(sqrt %o)}: center in unique real quadratic of Q(pi) at p=%o,%o (non-isomorphic quartics, CLV); QM excluded by #tors=%o>18\n",
            I, target, flds[1][1], flds[2][1], &*I;
        n := 0;
        RMEvidence(g, D, target, ~n);
        printf "RM      %-14o Q(sqrt %o) at all %o admissible p<200 (evidence; the lower bound End^0 <> Q is cited)\n",
            I, target, n;
    end if;
end for;
assert nsimple eq #rows;
assert nendz eq #[ i : i in [1..#rows] | rows[i][4] ne 2 ];   // every non-RM row
printf "PART A: all %o census curves geometrically simple\n", nsimple;
printf "PART B: End(Jac_Qbar) = Z for all %o non-RM curves\n", nendz;
printf "PART C: End^0 in {Q, F} certified for the RM rows; the RM lower bound is cited, with Frobenius evidence\n";

// ---- Part D: the [2,22] subsection (both displayed curves) ----
// the first displayed curve IS the [2,22] table row: take it from there
r22 := rows[[ i : i in [1..#rows] | rows[i][1] eq [2,22] ][1]];
f22s := [ < R!r22[2], R!r22[3] >,
          < 30*x^5-120*x^4-259*x^3+18*x^2+138*x+36, x^2+x > ];
for k in [1..2] do
    f, h := Explode(f22s[k]);
    Cs := SimplifiedModel(HyperellipticCurve(f, h));
    J := Jacobian(Cs);
    I := Invariants(AbelianGroup(TorsionSubgroup(J)));
    assert I eq [2, 22];
    g := HyperellipticPolynomials(Cs);
    Ws := [ Cs![r[1], 0] : r in Roots(g) ];
    if IsOdd(Degree(g)) then Ws cat:= [ pt : pt in PointsAtInfinity(Cs) ]; end if;
    assert #Ws eq 2;
    found := false;
    for pt in Points(Cs : Bound := 300) do
        if pt[3] eq 0 and IsEven(Degree(g)) then continue; end if;
        if pt in Ws then continue; end if;
        if pt[3] ne 0 and pt[2] eq 0 then continue; end if;
        if &and[ o22 where o22 := 22*D eq J!0 and 11*D ne J!0 and 2*D ne J!0
                 where D := J![pt, W] : W in Ws ] then
            printf "[2,22] curve %o: exact torsion [2,22], P=%o with [P-W_i] of order 22 for both W_i\n", k, pt;
            found := true; break;
        end if;
    end for;
    assert found;
    // simplicity + RM evidence for this model
    gi := IntSextic(f, h);
    D22 := Z!Discriminant(gi);
    p0, chi0 := StrictPrime(gi, D22, 500);
    assert p0 ne 0;
    n := 0;
    RMEvidence(gi, D22, 5, ~n);
    printf "[2,22] curve %o: simple (p=%o), RM-by-sqrt(5) evidence at %o primes\n", k, p0, n;
end for;

printf "ALL CERTIFICATES VERIFIED (%o census curves + the 2 curves of the [2,22] subsection, %.1o s)\n", nsimple, Cputime() - t0;
quit;
