//////////////////////////////////////////////////////////////////////
//  [2,24] W-split cubic-contact cover workbench.
//
//  This follows the open non-d=0 route:
//
//      f = H^2 + Kappa*(x^2 + U*x + V)^3
//
//  on the A(8) chart, intersected with the W-split condition.  The
//  W-split surface is generated by beta via
//
//      beta^2*(2*d + a + beta^2)^2 - 4*(d^2+c)*beta^2 - b^2 = 0,
//
//  which is quadratic in p for fixed (r,t,beta).
//
//  Modes:
//    Mode:="stats"   : build the symbolic cover equations and report
//                      degrees/term counts.
//    Mode:="ff_disc" : finite-field W-split/contact survey, grouped by
//                      exact disc(q3)=U^2-4V fibers.
//    Mode:="tri_stats"
//                    : on disc(q3)=Delta, eliminate Kappa,H2,H1,H0
//                      triangularly from the top contact coefficients and
//                      report the residual equation sizes in
//                      (r,p,t,beta,U,H3).
//    Mode:="p_resultants"
//                    : after the triangular reduction, eliminate p against
//                      the W-split equation by resultants.  Optional exact
//                      slices: FixU, FixBeta, FixTRatio.
//    Mode:="zero_slice"
//                    : with FixU and FixBeta set, solve/analyze the exact
//                      zero-dimensional slice in variables (r,p,t,M).
//    Mode:="zero_slice_ff"
//                    : finite-field direct scan of the triangular fixed
//                      Delta equations.  If FixU/FixBeta are not set, scan
//                      all slices and report the most populated ones.
//    Mode:="slice_grid_ff"
//                    : finite-field scan of small integer (U,beta) slices,
//                      scored across primes to select exact candidates.
//    Mode:="slice_grid_rat_ff"
//                    : finite-field scan of small rational (U,beta) slices
//                      of bounded numerator/denominator height RatGridH.
//    Mode:="beta0_u0_branches"
//                    : exact branch analysis for the recurring
//                      Delta=2,U=0,beta=0 slice, where W splits into
//                      t=1 and p=r branches.
//    Mode:="beta0_u0_branch_search"
//                    : bounded rational search on those two branches,
//                      using the residual linear in M^2.
//    Mode:="fixed_slice_search"
//                    : for fixed Delta,U,beta, search rational (r,t),
//                      solve W for rational p, then solve residuals in M.
//
//  Usage:
//    magma -b Mode:=stats \
//        code/agent_a2_24_wsplit_contact_cover.m
//
//    magma -b Mode:=ff_disc Primes:="11,13,17" \
//        code/agent_a2_24_wsplit_contact_cover.m
//////////////////////////////////////////////////////////////////////

SetColumns(0);

if not assigned MemGB then
    MemGB := 4;
elif Type(MemGB) eq MonStgElt then
    MemGB := StringToInteger(MemGB);
end if;
SetMemoryLimit(MemGB*10^9);

if not assigned Mode then
    Mode := "ff_disc";
elif Type(Mode) ne MonStgElt then
    Mode := Sprint(Mode);
end if;

if not assigned Primes then
    Primes := "11,13,17";
elif Type(Primes) ne MonStgElt then
    Primes := Sprint(Primes);
end if;
PrimeList := [StringToInteger(s) : s in Split(Primes, ",")];

Z := Integers();
Q := Rationals();

function ParseQ(x)
    if Type(x) eq MonStgElt then
        parts := Split(x, "/");
        if #parts eq 1 then
            return Q!StringToInteger(parts[1]);
        end if;
        return Q!StringToInteger(parts[1])/Q!StringToInteger(parts[2]);
    end if;
    return Q!x;
end function;

if not assigned SampleLimit then
    SampleLimit := 12;
elif Type(SampleLimit) eq MonStgElt then
    SampleLimit := StringToInteger(SampleLimit);
end if;

if not assigned TopN then
    TopN := 8;
elif Type(TopN) eq MonStgElt then
    TopN := StringToInteger(TopN);
end if;

if not assigned IncludeBeta0 then
    IncludeBeta0 := true;
elif Type(IncludeBeta0) eq MonStgElt then
    IncludeBeta0 := IncludeBeta0 in {"true", "True", "1", "yes", "Yes"};
end if;

if not assigned Delta then
    Delta := Q!2;
else
    Delta := ParseQ(Delta);
end if;

HasFixU := false;
FixUVal := Q!0;
if assigned FixU then
    HasFixU := true;
    FixUVal := ParseQ(FixU);
end if;

HasFixBeta := false;
FixBetaVal := Q!0;
if assigned FixBeta then
    HasFixBeta := true;
    FixBetaVal := ParseQ(FixBeta);
end if;

HasFixTRatio := false;
FixTRatioVal := Q!0;
if assigned FixTRatio then
    HasFixTRatio := true;
    FixTRatioVal := ParseQ(FixTRatio);
end if;

if not assigned DoFactor then
    DoFactor := false;
elif Type(DoFactor) eq MonStgElt then
    DoFactor := DoFactor in {"true", "True", "1", "yes", "Yes"};
end if;

if not assigned DoVariety then
    DoVariety := true;
elif Type(DoVariety) eq MonStgElt then
    DoVariety := DoVariety in {"true", "True", "1", "yes", "Yes"};
end if;

if not assigned UseRab then
    UseRab := true;
elif Type(UseRab) eq MonStgElt then
    UseRab := UseRab in {"true", "True", "1", "yes", "Yes"};
end if;

if not assigned DoEliminateM then
    DoEliminateM := false;
elif Type(DoEliminateM) eq MonStgElt then
    DoEliminateM := DoEliminateM in {"true", "True", "1", "yes", "Yes"};
end if;

if not assigned SearchH then
    SearchH := 10;
elif Type(SearchH) eq MonStgElt then
    SearchH := StringToInteger(SearchH);
end if;

if not assigned UBound then
    UBound := 3;
elif Type(UBound) eq MonStgElt then
    UBound := StringToInteger(UBound);
end if;

if not assigned BetaBound then
    BetaBound := 3;
elif Type(BetaBound) eq MonStgElt then
    BetaBound := StringToInteger(BetaBound);
end if;

if not assigned RatGridH then
    RatGridH := 2;
elif Type(RatGridH) eq MonStgElt then
    RatGridH := StringToInteger(RatGridH);
end if;

if not assigned SkipBeta0 then
    SkipBeta0 := true;
elif Type(SkipBeta0) eq MonStgElt then
    SkipBeta0 := SkipBeta0 in {"true", "True", "1", "yes", "Yes"};
end if;

procedure Inc(~A, key)
    if not IsDefined(A, key) then
        A[key] := 0;
    end if;
    A[key] +:= 1;
end procedure;

procedure IncBy(~A, key, n)
    if not IsDefined(A, key) then
        A[key] := 0;
    end if;
    A[key] +:= n;
end procedure;

procedure AddSample(~samples, item, lim)
    if #samples lt lim then
        Append(~samples, item);
    end if;
end procedure;

function TopPairs(A, n)
    pairs := [<A[k], k> : k in Keys(A)];
    Sort(~pairs);
    out := [];
    for j in [1..Minimum(n, #pairs)] do
        idx := #pairs - j + 1;
        Append(~out, <pairs[idx][2], pairs[idx][1]>);
    end for;
    return out;
end function;

function TwoRankFF(fp)
    degs := [Degree(g[1]) : g in Factorization(fp)];
    k := #degs;
    even := 0;
    for mask in [0..2^k-1] do
        ss := 0;
        for i in [1..k] do
            if (mask div 2^(i-1)) mod 2 eq 1 then
                ss +:= degs[i];
            end if;
        end for;
        if ss mod 2 eq 0 then
            even +:= 1;
        end if;
    end for;
    return Ilog2(even) - 1;
end function;

function IsEvenSextic(fp)
    return Coefficient(fp,1) eq 0 and Coefficient(fp,3) eq 0
           and Coefficient(fp,5) eq 0;
end function;

function A8fFF(x, rv, pv, tv)
    e := tv^2 - 2*pv*tv/rv;
    d := e + 2*pv - rv^2;
    lambda := rv/tv;
    u := pv + rv*tv - 2*rv;
    v := e + rv^2 - rv*pv - rv^2*tv + 3*pv*tv - rv*tv^2;
    a := rv^2 - lambda;
    b := 2*rv*pv - 2*lambda*(pv + rv*tv) + 2*rv*lambda;
    c := pv^2 + 2*pv*rv^2 - rv^4 - rv^3*tv - rv*pv^2/tv
         - lambda*(rv^2 + e)
         + 2*lambda*(rv*pv + rv^2*tv - 3*pv*tv + rv*tv^2);
    Qpoly := x^2 + d;
    q := a*x^2 + b*x + c;
    g8 := x^2 + u*x + v;
    f := q*(Qpoly^2 + q);
    L := rv*x + (pv - rv^2);
    ellBase := -(q + Qpoly*L);
    return f, g8, ellBase, d;
end function;

function SplitWPvalsFF(rv, tv, bv)
    F := Parent(rv);
    Pp<pp> := PolynomialRing(F);
    e := tv^2 - 2*pp*tv/rv;
    d := e + 2*pp - rv^2;
    lambda := rv/tv;
    a := rv^2 - lambda;
    b := 2*rv*pp - 2*lambda*(pp + rv*tv) + 2*rv*lambda;
    c := pp^2 + 2*pp*rv^2 - rv^4 - rv^3*tv - rv*pp^2/tv
         - lambda*(rv^2 + e)
         + 2*lambda*(rv*pp + rv^2*tv - 3*pp*tv + rv*tv^2);
    E := bv^2*(2*d + a + bv^2)^2 - 4*(d^2 + c)*bv^2 - b^2;
    En := Numerator(E);
    if En eq 0 or Degree(En) lt 1 then
        return [], En eq 0;
    end if;
    return [rt[1] : rt in Roots(En)], false;
end function;

function SplitWPvalsQ(rv, tv, bv)
    Pp<pp> := PolynomialRing(Q);
    e := tv^2 - 2*pp*tv/rv;
    d := e + 2*pp - rv^2;
    lambda := rv/tv;
    a := rv^2 - lambda;
    b := 2*rv*pp - 2*lambda*(pp + rv*tv) + 2*rv*lambda;
    c := pp^2 + 2*pp*rv^2 - rv^4 - rv^3*tv - rv*pp^2/tv
         - lambda*(rv^2 + e)
         + 2*lambda*(rv*pp + rv^2*tv - 3*pp*tv + rv*tv^2);
    E := bv^2*(2*d + a + bv^2)^2 - 4*(d^2 + c)*bv^2 - b^2;
    En := Numerator(E);
    if En eq 0 or Degree(En) lt 1 then
        return [];
    end if;
    return [rt[1] : rt in Roots(En)];
end function;

function ContactClassesFF(J, f)
    // Return one row per contact conic q3=u, deduplicating D and -D.
    P := Parent(f);
    x := P.1;
    F := BaseRing(P);
    O := J!0;
    rows := [];
    seen := AssociativeArray();
    for Uv in F do
    for Vv in F do
        u := x^2 + Uv*x + Vv;
        disc := Discriminant(u);
        if disc eq 0 then
            continue;
        end if;
        for A in F do
        for B in F do
            v := A*x + B;
            if (f - v^2) mod u ne 0 then
                continue;
            end if;
            ok := true;
            try
                D := elt<J | u, v>;
            catch e
                ok := false;
            end try;
            if not ok or D eq O or 3*D ne O then
                continue;
            end if;
            key := Sprint(u);
            if IsDefined(seen, key) then
                continue;
            end if;
            seen[key] := true;
            Append(~rows, <u, IsSquare(disc), disc>);
        end for;
        end for;
    end for;
    end for;
    return rows;
end function;

function BaseKey(rr, pp, tt)
    return Sprintf("%o|%o|%o", rr, pp, tt);
end function;

function TermCount(poly)
    if poly eq 0 then
        return 0;
    end if;
    return #Monomials(poly);
end function;

function TDeg(poly)
    if poly eq 0 then
        return -1;
    end if;
    return TotalDegree(poly);
end function;

function HeightRationals(HH)
    vals := [];
    for den in [1..HH] do
        for num in [-HH..HH] do
            if GCD(num, den) eq 1 then
                Append(~vals, Q!num/den);
            end if;
        end for;
    end for;
    return Sort(Setseq(Seqset(vals)));
end function;

function TriangularSystem(R, DeltaVal)
    r := R.1; p := R.2; t := R.3; beta := R.4; U := R.5; M := R.6;
    F := FieldOfFractions(R);
    P<X> := PolynomialRing(F);

    rF := F!r; pF := F!p; tF := F!t; bF := F!beta;
    UF := F!U; MF := F!M; DeltaF := F!DeltaVal;
    VF := (UF^2 - DeltaF)/4;

    e := tF^2 - 2*pF*tF/rF;
    d := e + 2*pF - rF^2;
    lambda := rF/tF;
    a := rF^2 - lambda;
    b := 2*rF*pF - 2*lambda*(pF + rF*tF) + 2*rF*lambda;
    c := pF^2 + 2*pF*rF^2 - rF^4 - rF^3*tF - rF*pF^2/tF
         - lambda*(rF^2 + e)
         + 2*lambda*(rF*pF + rF^2*tF - 3*pF*tF + rF*tF^2);
    Qpoly := X^2 + d;
    q := a*X^2 + b*X + c;
    f := q*(Qpoly^2 + q);
    fc := [Coefficient(f, i) : i in [0..6]];

    K := fc[7] - MF^2;
    H2 := (fc[6] - 3*K*UF)/(2*MF);
    H1 := (fc[5] - H2^2 - 3*K*(UF^2 + VF))/(2*MF);
    H0 := (fc[4] - 2*H2*H1 - K*(UF^3 + 6*UF*VF))/(2*MF);

    R2 := fc[3] - (H1^2 + 2*H2*H0) - K*(3*UF^2*VF + 3*VF^2);
    R1 := fc[2] - 2*H1*H0 - K*(3*UF*VF^2);
    R0 := fc[1] - H0^2 - K*VF^3;
    Wexpr := bF^2*(2*d + a + bF^2)^2 - 4*(d^2 + c)*bF^2 - b^2;

    return [R!Numerator(R2), R!Numerator(R1), R!Numerator(R0)],
           R!Numerator(Wexpr);
end function;

function ApplyExactSlices(poly, R)
    vals := [R.i : i in [1..Rank(R)]];
    if HasFixTRatio then
        vals[3] := R!FixTRatioVal * R.1;
    end if;
    if HasFixBeta then
        vals[4] := R!FixBetaVal;
    end if;
    if HasFixU then
        vals[5] := R!FixUVal;
    end if;
    return Evaluate(poly, vals);
end function;

procedure RunStats()
    R<r,p,t,beta,U,V,H0,H1,H2,H3,Kappa> := PolynomialRing(Q, 11);
    F := FieldOfFractions(R);
    P<X> := PolynomialRing(F);

    rF := F!r; pF := F!p; tF := F!t; bF := F!beta;
    UF := F!U; VF := F!V;
    H0F := F!H0; H1F := F!H1; H2F := F!H2; H3F := F!H3;
    KF := F!Kappa;

    e := tF^2 - 2*pF*tF/rF;
    d := e + 2*pF - rF^2;
    lambda := rF/tF;
    a := rF^2 - lambda;
    b := 2*rF*pF - 2*lambda*(pF + rF*tF) + 2*rF*lambda;
    c := pF^2 + 2*pF*rF^2 - rF^4 - rF^3*tF - rF*pF^2/tF
         - lambda*(rF^2 + e)
         + 2*lambda*(rF*pF + rF^2*tF - 3*pF*tF + rF*tF^2);
    Qpoly := X^2 + d;
    q := a*X^2 + b*X + c;
    f := q*(Qpoly^2 + q);
    q3 := X^2 + UF*X + VF;
    H := H3F*X^3 + H2F*X^2 + H1F*X + H0F;
    Diff := f - H^2 - KF*q3^3;
    contactEqs := [R!Numerator(Coefficient(Diff, i)) : i in [0..6]];
    Wexpr := bF^2*(2*d + a + bF^2)^2 - 4*(d^2 + c)*bF^2 - b^2;
    WsplitEq := R!Numerator(Wexpr);
    DiscEq := U^2 - 4*V;

    print "WSPLIT_CONTACT_COVER_STATS";
    print "variables: r,p,t,beta,U,V,H0,H1,H2,H3,Kappa";
    print "contact equations are coeffs of f-H^2-Kappa*q3^3 in degrees 0..6";
    for i in [1..#contactEqs] do
        printf " contact_c%o total_degree=%o terms=%o\n",
            i-1, TDeg(contactEqs[i]), TermCount(contactEqs[i]);
    end for;
    printf " wsplit total_degree=%o terms=%o\n",
        TDeg(WsplitEq), TermCount(WsplitEq);
    printf " disc_q3 equation %o total_degree=%o terms=%o\n",
        DiscEq, TDeg(DiscEq), TermCount(DiscEq);
    print "wsplit_factorization";
    print Factorization(WsplitEq);
    print "stats_done";
end procedure;

procedure RunTriStats()
    R<r,p,t,beta,U,M> := PolynomialRing(Q, 6);
    resids, Wsplit := TriangularSystem(R, Delta);

    polys := [
        <"residual_c2", resids[1]>,
        <"residual_c1", resids[2]>,
        <"residual_c0", resids[3]>,
        <"wsplit", Wsplit>
    ];

    print "WSPLIT_CONTACT_TRIANGULAR_STATS";
    print "Delta", Delta;
    print "variables: r,p,t,beta,U,M where M=H3 and V=(U^2-Delta)/4";
    print "chart assumptions: M != 0, r != 0, t != 0";
    for row in polys do
        printf " %o total_degree=%o terms=%o\n",
            row[1], TDeg(row[2]), TermCount(row[2]);
    end for;
    print "triangular_stats_done";
end procedure;

procedure RunPResultants()
    R<r,p,t,beta,U,M> := PolynomialRing(Q, 6);
    resids0, W0 := TriangularSystem(R, Delta);
    names := ["residual_c2", "residual_c1", "residual_c0"];

    W := ApplyExactSlices(W0, R);
    resids := [ApplyExactSlices(f, R) : f in resids0];

    print "WSPLIT_CONTACT_P_RESULTANTS";
    print "Delta", Delta;
    print "slices",
          HasFixU select Sprintf("FixU=%o", FixUVal) else "FixU=free",
          HasFixBeta select Sprintf("FixBeta=%o", FixBetaVal) else "FixBeta=free",
          HasFixTRatio select Sprintf("FixTRatio=%o", FixTRatioVal) else "FixTRatio=free";
    print "variables: r,p,t,beta,U,M; p is eliminated by Resultant(W,residual,p)";
    printf " wsplit sliced total_degree=%o terms=%o degree_p=%o\n",
        TDeg(W), TermCount(W), Degree(W, p);
    for i in [1..#resids] do
        printf " %o sliced total_degree=%o terms=%o degree_p=%o\n",
            names[i], TDeg(resids[i]), TermCount(resids[i]), Degree(resids[i], p);
    end for;

    resultants := [];
    for i in [1..#resids] do
        if W eq 0 or resids[i] eq 0 then
            Append(~resultants, R!0);
            printf " resultant_%o is zero because input is zero\n", names[i];
            continue;
        end if;
        Ri := Resultant(W, resids[i], p);
        Append(~resultants, Ri);
        printf " resultant_%o total_degree=%o terms=%o\n",
            names[i], TDeg(Ri), TermCount(Ri);
    end for;

    nonzero := [f : f in resultants | f ne 0];
    if #nonzero ge 2 then
        g := nonzero[1];
        for i in [2..#nonzero] do
            g := GCD(g, nonzero[i]);
        end for;
        printf " common_gcd total_degree=%o terms=%o\n", TDeg(g), TermCount(g);
        if DoFactor and g ne 0 then
            print " common_gcd_factorization";
            print Factorization(g);
        end if;
    end if;
    print "p_resultants_done";
end procedure;

procedure RunZeroSlice()
    if not (HasFixU and HasFixBeta) then
        error "Mode zero_slice requires FixU and FixBeta";
    end if;

    R<r,p,t,beta,U,M> := PolynomialRing(Q, 6);
    resids0, W0 := TriangularSystem(R, Delta);
    if UseRab then
        S<rr,pp,tt,MM,zz> := PolynomialRing(Q, 5);
    else
        S<rr,pp,tt,MM> := PolynomialRing(Q, 4);
    end if;
    phi := hom<R -> S | rr, pp, tt, S!FixBetaVal, S!FixUVal, MM>;
    polys := [phi(f) : f in resids0 cat [W0]];
    names := ["residual_c2", "residual_c1", "residual_c0", "wsplit"];
    if UseRab then
        Append(~polys, zz*rr*tt*MM - 1);
        Append(~names, "rab_r_t_M");
    end if;

    print "WSPLIT_CONTACT_ZERO_SLICE";
    print "Delta", Delta, "FixU", FixUVal, "FixBeta", FixBetaVal;
    print "UseRab", UseRab;
    print UseRab select "variables: rr,pp,tt,MM,zz" else "variables: rr,pp,tt,MM";
    for i in [1..#polys] do
        printf " %o total_degree=%o terms=%o\n",
            names[i], TDeg(polys[i]), TermCount(polys[i]);
    end for;

    I := ideal<S | polys>;
    dim := Dimension(I);
    printf " ideal_dimension=%o\n", dim;
    if dim eq 0 then
        printf " ideal_degree=%o\n", Degree(I);
        if DoVariety then
            V := Variety(I);
            printf " rational_variety_count=%o\n", #V;
            for P in V do
                printf "  point r=%o p=%o t=%o M=%o\n", P[1], P[2], P[3], P[4];
            end for;
        end if;
    end if;
    if DoFactor then
        G := GroebnerBasis(I);
        print " groebner_basis";
        for g in G do
            printf "  degree=%o terms=%o poly=%o\n", TDeg(g), TermCount(g), g;
        end for;
    end if;
    print "zero_slice_done";
end procedure;

procedure RunZeroSliceFF()
    print "WSPLIT_CONTACT_ZERO_SLICE_FF";
    print "Delta", Delta, "Primes", PrimeList,
          HasFixU select Sprintf("FixU=%o", FixUVal) else "FixU=free",
          HasFixBeta select Sprintf("FixBeta=%o", FixBetaVal) else "FixBeta=free";
    print "columns: ell total_solutions non_d0_solutions populated_slices top_slices";

    for ell in PrimeList do
        F := GF(ell);
        R<r,p,t,beta,U,M> := PolynomialRing(F, 6);
        DeltaF := F!Delta;
        resids, Wpoly := TriangularSystem(R, DeltaF);
        Uvals := HasFixU select [F!FixUVal] else [u : u in F];
        Bvals := HasFixBeta select [F!FixBetaVal] else [b : b in F];
        sliceHist := AssociativeArray();
        sliceNonD0Hist := AssociativeArray();
        samples := [];
        total := 0;
        nonD0 := 0;
        for Uv in Uvals do
        for bv in Bvals do
            for rr in F do
                if rr eq 0 then
                    continue;
                end if;
                for tt in F do
                    if tt eq 0 or rr*tt eq 1 then
                        continue;
                    end if;
                    pvals, ident := SplitWPvalsFF(rr, tt, bv);
                    if ident then
                        continue;
                    end if;
                    for pp in pvals do
                        for Mv in F do
                            if Mv eq 0 then
                                continue;
                            end if;
                            vals := [rr, pp, tt, bv, Uv, Mv];
                            if &and[Evaluate(f, vals) eq 0 : f in resids] then
                                total +:= 1;
                                skey := Sprintf("U=%o beta=%o", Z!Uv, Z!bv);
                                Inc(~sliceHist, skey);
                                dnum := rr*tt^2 - 2*pp*tt + 2*pp*rr - rr^3;
                                if dnum ne 0 then
                                    nonD0 +:= 1;
                                    Inc(~sliceNonD0Hist, skey);
                                    AddSample(~samples, <Uv,bv,rr,pp,tt,Mv,dnum>, SampleLimit);
                                end if;
                            end if;
                        end for;
                    end for;
                end for;
            end for;
        end for;
        end for;
        top := TopPairs(sliceHist, TopN);
        topNonD0 := TopPairs(sliceNonD0Hist, TopN);
        printf "%o %o %o %o %o\n", ell, total, nonD0, #Keys(sliceHist), top;
        print "  top_non_d0", topNonD0;
        print "  samples";
        for s in samples do
            print "   ", s;
        end for;
    end for;
    print "zero_slice_ff_done";
end procedure;

function CountTriSliceFF(F, resids, uv, bv)
    total := 0;
    nonD0 := 0;
    for rr in F do
        if rr eq 0 then
            continue;
        end if;
        for tt in F do
            if tt eq 0 or rr*tt eq 1 then
                continue;
            end if;
            pvals, ident := SplitWPvalsFF(rr, tt, bv);
            if ident then
                continue;
            end if;
            for pp in pvals do
                for Mv in F do
                    if Mv eq 0 then
                        continue;
                    end if;
                    vals := [rr, pp, tt, bv, uv, Mv];
                    if &and[Evaluate(f, vals) eq 0 : f in resids] then
                        total +:= 1;
                        dnum := rr*tt^2 - 2*pp*tt + 2*pp*rr - rr^3;
                        if dnum ne 0 then
                            nonD0 +:= 1;
                        end if;
                    end if;
                end for;
            end for;
        end for;
    end for;
    return total, nonD0;
end function;

procedure RunSliceGridFF()
    candidates := [];
    for ui in [-UBound..UBound] do
        for bi in [-BetaBound..BetaBound] do
            if SkipBeta0 and bi eq 0 then
                continue;
            end if;
            Append(~candidates, <ui, bi>);
        end for;
    end for;

    print "WSPLIT_CONTACT_SLICE_GRID_FF";
    print "Delta", Delta, "Primes", PrimeList, "UBound", UBound,
          "BetaBound", BetaBound, "SkipBeta0", SkipBeta0;
    print "candidate_count", #candidates;

    rows := [];
    for cand in candidates do
        ui := cand[1];
        bi := cand[2];
        totals := [];
        nond0s := [];
        for ell in PrimeList do
            F := GF(ell);
            R<r,p,t,beta,U,M> := PolynomialRing(F, 6);
            resids, Wpoly := TriangularSystem(R, F!Delta);
            tot, nd := CountTriSliceFF(F, resids, F!ui, F!bi);
            Append(~totals, tot);
            Append(~nond0s, nd);
        end for;
        minND := (#nond0s eq 0) select 0 else Minimum(nond0s);
        sumND := &+nond0s;
        Append(~rows, <minND, sumND, ui, bi, totals, nond0s>);
    end for;
    Sort(~rows);
    print "top_slices_by_min_then_sum";
    for j in [1..Minimum(TopN, #rows)] do
        row := rows[#rows-j+1];
        printf "  U=%o beta=%o min_non_d0=%o sum_non_d0=%o totals=%o non_d0=%o\n",
            row[3], row[4], row[1], row[2], row[5], row[6];
    end for;
    print "slice_grid_ff_done";
end procedure;

procedure RunSliceGridRatFF()
    uVals := HeightRationals(RatGridH);
    bVals := HeightRationals(RatGridH);
    candidates := [];
    for uv in uVals do
        for bv in bVals do
            if SkipBeta0 and bv eq 0 then
                continue;
            end if;
            Append(~candidates, <uv, bv>);
        end for;
    end for;

    print "WSPLIT_CONTACT_SLICE_GRID_RAT_FF";
    print "Delta", Delta, "Primes", PrimeList, "RatGridH", RatGridH,
          "SkipBeta0", SkipBeta0;
    print "candidate_count", #candidates;
    print "rational_grid_U", uVals;
    print "rational_grid_beta", bVals;

    rows := [<cand[1], cand[2], [Z | ], [Z | ]> : cand in candidates];
    for ell in PrimeList do
        F := GF(ell);
        R<r,p,t,beta,U,M> := PolynomialRing(F, 6);
        resids, Wpoly := TriangularSystem(R, F!Delta);
        for i in [1..#rows] do
            uv := rows[i][1];
            bv := rows[i][2];
            totals := rows[i][3];
            nond0s := rows[i][4];
            if (Denominator(uv) mod ell eq 0) or (Denominator(bv) mod ell eq 0) then
                Append(~totals, -1);
                Append(~nond0s, -1);
            else
                tot, nd := CountTriSliceFF(F, resids, F!uv, F!bv);
                Append(~totals, tot);
                Append(~nond0s, nd);
            end if;
            rows[i] := <uv, bv, totals, nond0s>;
        end for;
    end for;

    scored := [];
    for row in rows do
        validND := [n : n in row[4] | n ge 0];
        if #validND eq #PrimeList then
            minND := Minimum(validND);
            sumND := &+validND;
        else
            minND := -1;
            sumND := -1;
        end if;
        Append(~scored, <minND, sumND, row[1], row[2], row[3], row[4]>);
    end for;
    Sort(~scored);
    print "top_slices_by_min_then_sum";
    for j in [1..Minimum(TopN, #scored)] do
        row := scored[#scored-j+1];
        printf "  U=%o beta=%o min_non_d0=%o sum_non_d0=%o totals=%o non_d0=%o\n",
            row[3], row[4], row[1], row[2], row[5], row[6];
    end for;
    print "slice_grid_rat_ff_done";
end procedure;

procedure PrintIdealSummary(label, S, polys, rab)
    print label;
    for i in [1..#polys] do
        printf " eq%o total_degree=%o terms=%o\n", i, TDeg(polys[i]), TermCount(polys[i]);
    end for;
    I := ideal<S | polys>;
    dim := Dimension(I);
    printf " dimension=%o\n", dim;
    if dim eq 0 then
        printf " degree=%o\n", Degree(I);
    end if;
    if DoFactor then
        for i in [1..#polys] do
            if polys[i] ne 0 and TermCount(polys[i]) le 200 then
                printf " factor_eq%o=%o\n", i, Factorization(polys[i]);
            end if;
        end for;
    end if;
end procedure;

function StripRepeatedFactor(poly, fac)
    out := poly;
    while out ne 0 do
        q, rem := Quotrem(out, fac);
        if rem ne 0 then
            break;
        end if;
        out := q;
    end while;
    return out;
end function;

procedure RunBeta0U0Branches()
    R<r,p,t,beta,U,M> := PolynomialRing(Q, 6);
    resids, W0 := TriangularSystem(R, Q!2);

    print "WSPLIT_CONTACT_BETA0_U0_BRANCHES";
    print "Delta=2 U=0 beta=0";
    print "At beta=0, W is proportional to (t-1)^2*(p-r)^2 after clearing.";

    S1<r1,p1,M1,z1> := PolynomialRing(Q, 4);
    phi1 := hom<R -> S1 | r1, p1, S1!1, S1!0, S1!0, M1>;
    polys1 := [phi1(f) : f in resids];
    if UseRab then
        Append(~polys1, z1*r1*M1*(r1-1) - 1);
    end if;
    PrintIdealSummary("BRANCH_t_equals_1", S1, polys1, UseRab);
    if DoEliminateM then
        E1 := StripRepeatedFactor(polys1[1], M1);
        E3 := StripRepeatedFactor(polys1[3], M1);
        RM := Resultant(E1, E3, M1);
        printf " BRANCH_t_equals_1_resM total_degree=%o terms=%o\n",
            TDeg(RM), TermCount(RM);
        if DoFactor then
            print " BRANCH_t_equals_1_resM_factorization";
            print Factorization(RM);
        end if;
    end if;

    S2<r2,t2,M2,z2> := PolynomialRing(Q, 4);
    phi2 := hom<R -> S2 | r2, r2, t2, S2!0, S2!0, M2>;
    polys2 := [phi2(f) : f in resids];
    if UseRab then
        Append(~polys2, z2*r2*t2*M2*(r2*t2-1) - 1);
    end if;
    PrintIdealSummary("BRANCH_p_equals_r", S2, polys2, UseRab);
    if DoEliminateM then
        E1 := StripRepeatedFactor(StripRepeatedFactor(StripRepeatedFactor(polys2[1], M2), r2), t2);
        E3 := StripRepeatedFactor(StripRepeatedFactor(StripRepeatedFactor(polys2[3], M2), r2), t2);
        RM := Resultant(E1, E3, M2);
        printf " BRANCH_p_equals_r_resM total_degree=%o terms=%o\n",
            TDeg(RM), TermCount(RM);
        if DoFactor then
            print " BRANCH_p_equals_r_resM_factorization";
            print Factorization(RM);
        end if;
    end if;

    print "beta0_u0_branches_done";
end procedure;

procedure RunBeta0U0BranchSearch()
    R<r,p,t,beta,U,M> := PolynomialRing(Q, 6);
    resids, W0 := TriangularSystem(R, Q!2);
    vals := HeightRationals(SearchH);
    hits := [];

    S1<r1,p1,M1> := PolynomialRing(Q, 3);
    phi1 := hom<R -> S1 | r1, p1, S1!1, S1!0, S1!0, M1>;
    E1t := StripRepeatedFactor(phi1(resids[1]), M1);
    E3t := StripRepeatedFactor(phi1(resids[3]), M1);

    for rv in vals do
        if rv eq 0 or rv eq 1 then
            continue;
        end if;
        for pv in vals do
            c0 := Evaluate(E3t, [rv, pv, Q!0]);
            c1 := Evaluate(E3t, [rv, pv, Q!1]) - c0;
            if c1 eq 0 then
                continue;
            end if;
            Nv := -c0/c1;
            if Nv eq 0 then
                continue;
            end if;
            ok, Mv := IsSquare(Nv);
            if not ok then
                continue;
            end if;
            if Evaluate(E1t, [rv, pv, Mv]) ne 0 then
                continue;
            end if;
            dnum := rv - 2*pv + 2*pv*rv - rv^3;
            Append(~hits, <"t=1", rv, pv, Q!1, Mv, dnum>);
        end for;
    end for;

    S2<r2,t2,M2> := PolynomialRing(Q, 3);
    phi2 := hom<R -> S2 | r2, r2, t2, S2!0, S2!0, M2>;
    E1p := StripRepeatedFactor(StripRepeatedFactor(StripRepeatedFactor(phi2(resids[1]), M2), r2), t2);
    E3p := StripRepeatedFactor(StripRepeatedFactor(StripRepeatedFactor(phi2(resids[3]), M2), r2), t2);

    for rv in vals do
        if rv eq 0 then
            continue;
        end if;
        for tv in vals do
            if tv eq 0 or rv*tv eq 1 then
                continue;
            end if;
            c0 := Evaluate(E3p, [rv, tv, Q!0]);
            c1 := Evaluate(E3p, [rv, tv, Q!1]) - c0;
            if c1 eq 0 then
                continue;
            end if;
            Nv := -c0/c1;
            if Nv eq 0 then
                continue;
            end if;
            ok, Mv := IsSquare(Nv);
            if not ok then
                continue;
            end if;
            if Evaluate(E1p, [rv, tv, Mv]) ne 0 then
                continue;
            end if;
            dnum := rv*(tv^2 - 2*tv + 2*rv - rv^2);
            Append(~hits, <"p=r", rv, rv, tv, Mv, dnum>);
        end for;
    end for;

    print "WSPLIT_CONTACT_BETA0_U0_BRANCH_SEARCH";
    print "SearchH", SearchH, "hits", #hits;
    for h in hits do
        print " ", h;
    end for;
    print "beta0_u0_branch_search_done";
end procedure;

procedure RunFixedSliceSearch()
    if not (HasFixU and HasFixBeta) then
        error "Mode fixed_slice_search requires FixU and FixBeta";
    end if;
    R<r,p,t,beta,U,M> := PolynomialRing(Q, 6);
    resids, W0 := TriangularSystem(R, Delta);
    Pm<m> := PolynomialRing(Q);
    vals := HeightRationals(SearchH);
    hits := [];
    tested := 0;
    pcount := 0;
    for rv in vals do
        if rv eq 0 then
            continue;
        end if;
        for tv in vals do
            if tv eq 0 or rv*tv eq 1 then
                continue;
            end if;
            tested +:= 1;
            pvals := [];
            try
                pvals := SplitWPvalsQ(rv, tv, FixBetaVal);
            catch e
                pvals := [];
            end try;
            for pv in pvals do
                pcount +:= 1;
                phi := hom<R -> Pm | Pm!rv, Pm!pv, Pm!tv,
                                      Pm!FixBetaVal, Pm!FixUVal, m>;
                univs := [phi(f) : f in resids];
                g := univs[1];
                for i in [2..#univs] do
                    g := GCD(g, univs[i]);
                end for;
                if g eq 0 or Degree(g) lt 1 then
                    continue;
                end if;
                for rt in Roots(g) do
                    mv := rt[1];
                    if mv eq 0 then
                        continue;
                    end if;
                    dnum := rv*tv^2 - 2*pv*tv + 2*pv*rv - rv^3;
                    Append(~hits, <rv,pv,tv,mv,dnum>);
                end for;
            end for;
        end for;
    end for;
    print "WSPLIT_CONTACT_FIXED_SLICE_SEARCH";
    print "Delta", Delta, "FixU", FixUVal, "FixBeta", FixBetaVal,
          "SearchH", SearchH, "tested_rt", tested, "pcount", pcount,
          "hits", #hits;
    for h in hits do
        print " ", h;
    end for;
    print "fixed_slice_search_done";
end procedure;

procedure RunFFDisc()
    print "WSPLIT_CONTACT_DISC_SURVEY_START";
    print "Primes", PrimeList, "SampleLimit", SampleLimit, "TopN", TopN,
          "IncludeBeta0", IncludeBeta0;
    print "columns: ell beta_points unique_bases smooth order8 rank2 j3 contact_bases contact_conics raw_beta_contact split_conics irreducible_conics non_d0_conics non_d0_irred_conics d0_conics";

    for ell in PrimeList do
        F := GF(ell);
        P<x> := PolynomialRing(F);
        baseRecs := AssociativeArray();
        baseBetaMult := AssociativeArray();
        betaPoints := 0;
        betaDegenerate := 0;
        duplicateBeta := 0;

        for rr in F do
            if rr eq 0 then
                continue;
            end if;
            for tt in F do
                if tt eq 0 or rr*tt eq 1 then
                    continue;
                end if;
                for bb in F do
                    if bb eq 0 and not IncludeBeta0 then
                        continue;
                    end if;
                    pvals, ident := SplitWPvalsFF(rr, tt, bb);
                    if ident then
                        betaDegenerate +:= 1;
                        continue;
                    end if;
                    for pp in pvals do
                        betaPoints +:= 1;
                        key := BaseKey(rr, pp, tt);
                        if IsDefined(baseRecs, key) then
                            duplicateBeta +:= 1;
                            baseBetaMult[key] +:= 1;
                        else
                            baseRecs[key] := <rr, pp, tt>;
                            baseBetaMult[key] := 1;
                        end if;
                    end for;
                end for;
            end for;
        end for;

        smooth := 0;
        order8 := 0;
        rank2 := 0;
        j3 := 0;
        contactBases := 0;
        contactConics := 0;
        rawBetaContact := 0;
        splitConics := 0;
        irredConics := 0;
        nonD0Conics := 0;
        nonD0IrredConics := 0;
        d0Conics := 0;
        discHist := AssociativeArray();
        discRawHist := AssociativeArray();
        discNonD0Hist := AssociativeArray();
        discNonD0IrredHist := AssociativeArray();
        betaMultHist := AssociativeArray();
        samples := [];
        nonD0IrredSamples := [];

        for key in Keys(baseRecs) do
            rec := baseRecs[key];
            rr := rec[1]; pp := rec[2]; tt := rec[3];
            f, g8, ellBase, dval := A8fFF(x, rr, pp, tt);
            if Degree(f) lt 5 or not IsSquarefree(f) or IsEvenSextic(f) then
                continue;
            end if;
            smooth +:= 1;
            J := Jacobian(HyperellipticCurve(f));
            O := J!0;
            v8 := (-ellBase) mod g8;
            ok8 := true;
            try
                D8 := elt<J | g8, v8>;
                if 8*D8 ne O or 4*D8 eq O then
                    ok8 := false;
                end if;
            catch e
                ok8 := false;
            end try;
            if not ok8 then
                continue;
            end if;
            order8 +:= 1;
            if TwoRankFF(f) lt 2 then
                continue;
            end if;
            rank2 +:= 1;
            if #J mod 3 ne 0 then
                continue;
            end if;
            j3 +:= 1;
            crows := ContactClassesFF(J, f);
            if #crows eq 0 then
                continue;
            end if;
            contactBases +:= 1;
            Inc(~betaMultHist, Sprint(baseBetaMult[key]));
            rawBetaContact +:= baseBetaMult[key]*#crows;
            for row in crows do
                u := row[1];
                split := row[2];
                disc := row[3];
                dkey := Z!disc;
                contactConics +:= 1;
                Inc(~discHist, dkey);
                IncBy(~discRawHist, dkey, baseBetaMult[key]);
                if split then
                    splitConics +:= 1;
                else
                    irredConics +:= 1;
                end if;
                if dval eq 0 then
                    d0Conics +:= 1;
                else
                    nonD0Conics +:= 1;
                    Inc(~discNonD0Hist, dkey);
                    if not split then
                        nonD0IrredConics +:= 1;
                        Inc(~discNonD0IrredHist, dkey);
                        AddSample(~nonD0IrredSamples,
                                  <dkey, rr, pp, tt, dval, u, baseBetaMult[key]>,
                                  SampleLimit);
                    end if;
                end if;
                AddSample(~samples,
                          <dkey, rr, pp, tt, dval, u, split, baseBetaMult[key]>,
                          SampleLimit);
            end for;
        end for;

        printf "%o %o %o %o %o %o %o %o %o %o %o %o %o %o\n",
            ell, betaPoints, #Keys(baseRecs), smooth, order8, rank2, j3,
            contactBases, contactConics, rawBetaContact, splitConics,
            irredConics, nonD0Conics, nonD0IrredConics, d0Conics;
        printf "  beta_degenerate=%o duplicate_beta=%o beta_mult_hist=%o\n",
            betaDegenerate, duplicateBeta,
            Sort([<k, betaMultHist[k]> : k in Keys(betaMultHist)]);
        print "  exact_disc_top_all", TopPairs(discHist, TopN);
        print "  exact_disc_top_raw_beta", TopPairs(discRawHist, TopN);
        print "  exact_disc_top_non_d0", TopPairs(discNonD0Hist, TopN);
        print "  exact_disc_top_non_d0_irred", TopPairs(discNonD0IrredHist, TopN);
        print "  samples";
        for s in samples do
            print "   ", s;
        end for;
        print "  non_d0_irred_samples";
        for s in nonD0IrredSamples do
            print "   ", s;
        end for;
    end for;

    print "WSPLIT_CONTACT_DISC_SURVEY_DONE";
end procedure;

if Mode eq "stats" then
    RunStats();
elif Mode eq "ff_disc" then
    RunFFDisc();
elif Mode eq "tri_stats" then
    RunTriStats();
elif Mode eq "p_resultants" then
    RunPResultants();
elif Mode eq "zero_slice" then
    RunZeroSlice();
elif Mode eq "zero_slice_ff" then
    RunZeroSliceFF();
elif Mode eq "slice_grid_ff" then
    RunSliceGridFF();
elif Mode eq "slice_grid_rat_ff" then
    RunSliceGridRatFF();
elif Mode eq "beta0_u0_branches" then
    RunBeta0U0Branches();
elif Mode eq "beta0_u0_branch_search" then
    RunBeta0U0BranchSearch();
elif Mode eq "fixed_slice_search" then
    RunFixedSliceSearch();
else
    error Sprintf("unknown Mode=%o", Mode);
end if;

quit;
