/* claude_ov_b4_raisesieve.gp -- Lane 4 (route B4): EXHAUSTIVE search of the
   2-rank-raise locus over the (6,2) stream.

   E: Y^2 = w^3+3w^2+2w+1 (conductor 92) has E(Q) = Z generated by G = (0,1)
   (rank 1, trivial torsion).  The (6,2) component of the quadratic-factor
   incidence of Flynn's order-11 family is birational to E, so its rational
   points are EXACTLY the members produced by n*G, n in Z.  Therefore sweeping
   n in [NLO,NHI] is an EXHAUSTIVE search of that component in that range --
   not a sample.

   For each member: build f = F_t, take the rational quadratic block, apply the
   Galois-stable Richelot isogeny, and record the factor type of the codomain.
   The codomain has generic type [2,4] (2-rank 1, proved symbolically); a
   raise to 2-rank >= 2 means torsion [2,22] and is exactly the condition
   "A1 = z0' - p' is a rational square" (the genus-3 cover of E).

   Usage:  gp -q -D parisize=... -D NLO=..,NHI=.. is not supported; instead
           echo 'NLO=1;NHI=40;read("claude_ov_b4_raisesieve.gp")' | gp -q
*/

read(strprintf("%s/claude_ov_b4_richelot.gp", if(type(B4DIR)=="t_STR", B4DIR, ".")));

NLO = if(type(NLO)=="t_INT", NLO, 1);
NHI = if(type(NHI)=="t_INT", NHI, 40);

x='x; t='t; u='u; v='v;
Fl(tt) = x^6+2*x^5+(2*tt+3)*x^4+2*x^3+(tt^2+1)*x^2+2*tt*(1-tt)*x+tt^2;
a2c(uu) = (uu-2)^4;
b1c(uu) = 2*(uu^5-5*uu^4+9*uu^3-8*uu^2+4*uu-2);

{
  my(E, G, nm=0, nraise=0, nfail=0);
  E = ellinit([0,3,0,2,1]);
  G = [0,1];
  for(n = NLO, NHI,
    if(n == 0, next);
    my(P, w0, Y0, uu);
    P = ellmul(E, G, n);
    if(#P < 2, next);
    w0 = P[1]; Y0 = P[2];
    uu = -w0;
    if(uu == 2 || uu == 1, next);
    for(sg = 0, 1,
      my(A,B,vv,ff,dv,r,ee1,ee0,g,rts);
      A = a2c(uu); B = b1c(uu);
      vv = (-B + (-1)^sg*4*(uu-1)*Y0)/(2*A);
      if(vv == 0, next);
      ff = Fl(t);
      dv = divrem(ff, x^2+uu*x+vv);
      r = dv[2];
      ee1 = polcoef(r,1,x); ee0 = polcoef(r,0,x);
      if(ee1 == 0 && ee0 == 0, next);
      g = if(ee1==0, ee0, if(ee0==0, ee1, gcd(ee1,ee0)));
      if(type(g) != "t_POL" || poldegree(g,t) < 1, next);
      rts = nfroots(, g);
      foreach(rts, t0,
        my(F, bl, out, degs, tr, hgt);
        F = subst(ff, t, t0);
        if(poldegree(F) < 5 || poldisc(F) == 0, next);
        bl = b4_blocks(F);
        if(#bl == 0, print("NOBLOCK n=", n, " sg=", sg); nfail++; next);
        nm++;
        hgt = #Str(numerator(uu)) + #Str(denominator(uu));
        my(seedtype = b4_factortype(F));
        if(b4_tworank(seedtype) >= 2,
          print("SEEDRAISE n=", n, " sg=", sg, " seedtype=", seedtype, " F=", F);
          nraise++);
        foreach(bl, br,
          my(rr = b4_resroots(br[2]));
          if(#rr == 0, print("NOD4 n=", n, " sg=", sg); nfail++);
          for(j = 1, #rr,
            out = b4_richelot(F, br[1], br[2], j);
            if(out[1] != 1, print("DEGEN n=", n, " sg=", sg, " j=", j, " code=", out[1]); nfail++; next);
            degs = b4_factortype(out[2]);
            tr = b4_tworank(degs);
            if(tr >= 2,
              nraise++;
              print("RAISE n=", n, " sg=", sg, " j=", j, " codtype=", degs, " 2rank=", tr);
              print("RAISE_F ", b4_intmodel(out[2]));
            );
            print("MEM n=", n, " sg=", sg, " j=", j, " uhgt=", hgt,
                  " seedtype=", seedtype, " codtype=", degs, " cod2rank=", tr);
          ));
      );
    );
    if(n % 5 == 0, print("PROGRESS n=", n, " members=", nm, " raises=", nraise));
  );
  print("SEARCH_DONE raisesieve NLO=", NLO, " NHI=", NHI, " members=", nm,
        " raises=", nraise, " failures=", nfail);
}
quit
