#!/usr/bin/env python3
"""
claude_ov_m612ap_combine2.py    lane 9 ([6,12])   2026-07-25

Combine the per-prime output of code/claude_ov_m612ap_sieve3.m (or of the
older sieve2.m, whose files lack the RES3/RES9 lines) into the Abel-Prym
Mordell-Weil sieve conclusion for the gatekeeper curve

    E8 : y^8 + A(x) y^4 + B(x) y^2 + C(x) = 0,  genus 4,  iota : y -> -y,
    alpha(P) = [P - iota P]  in  Pr = (1-iota) J(E8),   rank Pr(Q) = 1,
    alpha(P) = 0  <=>  P in {b1,b2}  (the two rational iota-fixed places).

Write Lambda = <W1,W2,W3> for the subgroup of Pr(Q) generated by the three
intrinsic classes found by claude_ov_m612ap_wfind.m.  Assume

    (SAT)   Pr(Q) = <W> + Pr(Q)_tors  for the reference class W = W2 = W3,

i.e. W generates Pr(Q) modulo torsion.  Then every rational point P of E8
has alpha(P) = d*W + t with t torsion, and for every good prime q,

    reduction of alpha(P)  =  [R - iota R]  for R = P mod q.

Three sieve variants, in decreasing strength and increasing rigour:

  V0 : uses  RES_j  = { d : [R-iotaR] = d*Wbar }.        Valid iff t = 0.
  V3 : uses  RES3_j = { e : 3[R-iotaR] = e*Wbar },
       admissible d = { d : 3d mod m in RES3 }.          Valid iff 3t = 0.
  V9 : uses  RES9_j, admissible d = { d : 9d mod m in RES9 }.  Valid iff 9t = 0.

#J(E8)(Q)_tors divides gcd_q #J(E8)(F_q) = 9, and at q = 7 the 3-primary
part of J(E8)(F_7) is (Z/3)^2, of exponent 3; hence 3t = 0 always and V3 is
UNCONDITIONAL given (SAT).  V9 is a redundant double-check.

Usage: python3 code/claude_ov_m612ap_combine2.py results/ap3 ap3
"""
import sys, os, glob
from math import gcd

def parse(fn):
    D = {}
    for line in open(fn):
        line = line.strip()
        if not line:
            continue
        t = line.split(" ", 1)
        D[t[0]] = t[1] if len(t) > 1 else ""
    return D

def seq(s):
    if s is None or s.strip() in ("", "-"):
        return []
    return [int(u) for u in s.strip().rstrip(",").split(",") if u != ""]

def factor(m):
    f = {}
    d, mm = 2, m
    while d * d <= mm:
        while mm % d == 0:
            f[d] = f.get(d, 0) + 1
            mm //= d
        d += 1
    if mm > 1:
        f[mm] = f.get(mm, 0) + 1
    return f

def main():
    wdir = sys.argv[1] if len(sys.argv) > 1 else "results/ap3"
    tag = sys.argv[2] if len(sys.argv) > 2 else "ap3"
    files = sorted(glob.glob(os.path.join(wdir, tag + "_q*.txt")),
                   key=lambda f: int(f.split("_q")[-1].split(".")[0]))
    rows, skipped = [], []
    for f in files:
        q = int(f.split("_q")[-1].split(".")[0])
        D = parse(f)
        if "SKIP" in D or "JORDER" not in D:
            skipped.append((q, D.get("SKIP", "no JORDER")))
            continue
        rows.append((q, D))

    print("=== Abel-Prym MW sieve, combination (E8 / [6,12] lane 9) ===")
    print("directory %s   usable primes: %d   skipped: %d"
          % (wdir, len(rows), len(skipped)))
    for q, why in skipped:
        print("  SKIP q=%-4d %s" % (q, why))
    if not rows:
        return
    print("primes: %s" % [q for q, _ in rows])

    # ---------------- torsion ------------------------------------------
    g = gh4 = 0
    for q, D in rows:
        g = gcd(g, int(D["JORDER"]))
        if "PRYMORD" in D:
            gh4 = gcd(gh4, int(D["PRYMORD"]))
    print("\n[torsion]  gcd_q #J(E8)(F_q) = %d   (bounds #J(E8)(Q)_tors)" % g)
    print("           gcd_q #J(E8)(F_q)/#J(E4)(F_q) = %d  (bounds #Pr(Q)_tors)" % gh4)
    for q, D in rows:
        inv = seq(D.get("JINV"))
        three = [i for i in inv if i % 3 == 0]
        exp3 = 1
        for i in inv:
            e = 0
            j = i
            while j % 3 == 0:
                j //= 3
                e += 1
            exp3 = max(exp3, 3 ** e)
        if exp3 <= 3:
            print("           exponent of J(E8)(F_%d)[3^oo] is %d  => 3*t = 0 for"
                  " every rational torsion class t" % (q, exp3))
            break

    # ---------------- saturation ---------------------------------------
    tested, divisible = {}, {}
    for q, D in rows:
        for ell in seq(D.get("TESTED")):
            tested.setdefault(ell, []).append(q)
        for ell in seq(D.get("DIVISIBLE")):
            divisible.setdefault(ell, []).append(q)
    survive = []
    print("\n[saturation]  ell can divide [Pr(Q)/tors : Lambda] only if the")
    print("  reference class is ell-divisible in J(E8)(F_q) for EVERY q with")
    print("  ell | #J(E8)(F_q).  One failure kills ell.")
    for ell in sorted(tested):
        ts, dv = tested[ell], divisible.get(ell, [])
        if len(dv) == len(ts):
            survive.append(ell)
            print("  ell = %-5d NOT ruled out  (%d/%d primes divisible: q in %s)"
                  % (ell, len(dv), len(ts), ts[:6]))
    print("  ell ruled out: %s" % sorted(set(tested) - set(survive)))
    print("  ell NOT ruled out: %s" % survive)

    # ---------------- raw discriminating power --------------------------
    print("\n[raw sieve power]  q : #E8(F_q) deg-1 places / non-iota-fixed /"
          " with class in <W> / ord(W mod q) / #Pr(F_q)")
    tot_nf = tot_in = 0
    for q, D in rows:
        nf = int(D.get("NONFIXED", 0))
        ins = len(seq(D.get("INS")))
        ords = seq(D.get("WORDERS"))
        m = max(ords) if ords else 0
        tot_nf += nf
        tot_in += ins
        print("   q = %-4d %-5s %-5d %-5d %-8d %s"
              % (q, D.get("NPLACES1", "?"), nf, ins, m, D.get("PRYMORD", "?")))
    if tot_nf:
        print("   TOTAL: %d of %d non-fixed F_q-points (%.2f%%) have Abel-Prym"
              " class in <W mod q>" % (tot_in, tot_nf, 100.0 * tot_in / tot_nf))

    # ---------------- the sieve ----------------------------------------
    def run(variant, mult, reskey):
        print("\n" + "=" * 68)
        print("SIEVE VARIANT %s   (constraint: %s)" % (variant,
              "alpha(P) = d*W exactly" if mult == 1
              else "%d*alpha(P) = %d*d*W, torsion of exponent | %d" % (mult, mult, mult)))
        allowed = {}     # ell^a -> set of residues of d
        users = {}
        used = 0
        for q, D in rows:
            ords = seq(D.get("WORDERS"))
            gok = seq(D.get("GENOK")) or [1, 1, 1]
            cand = []
            for j in (2, 3):
                if len(gok) >= j and gok[j - 1] == 1 and len(ords) >= j and ords[j - 1] > 1:
                    R = D.get("%s%d" % (reskey, j))
                    if R is None or R.strip() == "-":
                        continue
                    cand.append((ords[j - 1], set(seq(R))))
            if not cand:
                continue
            used += 1
            m = cand[0][0]
            Dq = set(range(m))
            for (mm, R) in cand:
                assert mm == m, "W2 and W3 have different orders at q=%d" % q
                Dq &= set(d for d in range(m) if (mult * d) % m in R)
            for ell, e in factor(m).items():
                for a in range(1, e + 1):
                    pk = ell ** a
                    A = set(d % pk for d in Dq)
                    if pk in allowed:
                        allowed[pk] &= A
                        users[pk].append(q)
                    else:
                        allowed[pk] = A
                        users[pk] = [q]
        print("primes contributing: %d" % used)
        # per ell, intersect the constraints coming from all powers
        byell = {}
        for pk in allowed:
            ell = min(factor(pk))
            byell.setdefault(ell, []).append(pk)
        M = 1
        total = 1
        for ell in sorted(byell):
            pks = sorted(byell[ell])
            top = pks[-1]
            A = set(range(top))
            for pk in pks:
                A &= set(d for d in range(top) if d % pk in allowed[pk])
            nq = max(len(users[pk]) for pk in pks)
            # largest ell^b dividing EVERY surviving residue
            b = 0
            while b < len(str(top)) * 4:
                if all(a % (ell ** (b + 1)) == 0 for a in A) and ell ** (b + 1) <= top:
                    b += 1
                else:
                    break
            print("  ell = %-5d top modulus %-8d (%d primes)  |allowed| = %-5d %s"
                  "   ell^%d | d" % (ell, top, nq, len(A),
                                     sorted(A)[:8] if len(A) <= 8 else "", b))
            total *= len(A)
            M *= ell ** b
        print("  --> d = 0 mod %d" % M)
        print("  --> classes of d surviving modulo lcm of all moduli: %d" % total)
        if total == 1:
            print("  --> the ONLY surviving class is d = 0 mod %d" % M)
        return M

    run("V0", 1, "RES")
    if any("RES32" in D for _, D in rows):
        run("V3", 3, "RES3")
        run("V9", 9, "RES9")
    else:
        print("\n(no RES3/RES9 lines in this directory -- sieve2 output, V0 only)")

if __name__ == "__main__":
    main()
