#!/usr/bin/env python3
# SUPERSEDED 2026-08-24: paper/scripts_and_data/verify_simple_torsion_table.m
# is now a STATIC data-driven script that reads paper/scripts_and_data/table1.txt
# (the machine-readable table data from which make_tables.py typesets the
# paper table).  Do NOT regenerate it from here -- this generator predates
# the data files and would clobber the data-driven version.  Kept for the
# record of how the original embedded-data scripts were produced.

"""Generate code/verify_simple_torsion_table.m — a Magma script that verifies
the exact torsion subgroup of every genus-2 curve in
paper/torsion_realizations.tex (the geometrically simple table), via

    CheckTorsion(I, fh):
      assert I eq Invariants(AbelianGroup(TorsionSubgroup(Jacobian(
          SimplifiedModel(HyperellipticCurve(R!fh[1], R!fh[2]))))));

Inputs: the witness dictionaries of code/claude_gen_torsion_table.py (the
script that generates the table itself), imported directly so the two can
never drift apart.  The seven NEW rows and the [2,2,2,10] literature row are
stored there as factored LaTeX displays; this script re-expands them from the
same factorizations (exact integer arithmetic) below.
Rows are ordered by coefficient size so the cheap checks run first.

NOTE: this verifies the exact torsion group of every displayed curve.  It does
not verify geometric simplicity or endomorphism claims; those are certified by
the LMFDB (database rows) and by data/claude_endz_certificates.txt /
data/claude_z31_rm_certificate.txt (non-database rows).

Run from the repository root:  python3 code/claude_gen_simple_table_check.py
Then:  cd paper/scripts_and_data && magma -b verify_simple_torsion_table.m
"""
import os, sys, importlib.util

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "paper", "scripts_and_data", "verify_simple_torsion_table.m")

spec = importlib.util.spec_from_file_location(
    "gen_table", os.path.join(ROOT, "code", "claude_gen_torsion_table.py"))
gen = importlib.util.module_from_spec(spec)
sys.argv = ["claude_gen_torsion_table.py", os.devnull]  # suppress its tex output
spec.loader.exec_module(gen)

def polymul(a, b):
    out = [0] * (len(a) + len(b) - 1)
    for i, x in enumerate(a):
        for j, y in enumerate(b):
            out[i + j] += x * y
    return out

def prod(*factors):
    # each factor is an ascending coefficient list
    poly = [1]
    for f in factors:
        poly = polymul(poly, f)
    return poly

# The NEW / LIT_ONLY rows of claude_gen_torsion_table.py are stored there as
# factored LaTeX displays (h = 0 for all of them); the factorizations below
# are transcribed from those displays and re-expanded exactly.
FACTORED = {
 "[2,2,14]":   prod([1,1], [9,1], [-115,2], [55,6], [2652,-220,3]),
 "[2,2,20]":   prod([-1], [-1,1], [1,6], [7,2], [1008,6217], [144,-161,21]),
 "[2,4,8]":    prod([0,1], [-5,3], [333,5], [576,23,16]),
 "[6,6]":      prod([0,1], [125,-69,39], [39,8,48]),
 "[2,2,2,8]":  prod([0,1], [1,1], [55**2,1], [99**2,1], [125**2,1]),
 "[2,2,4,4]":  prod([0,1], [36**2,1], [57**2,1], [64**2,1], [132**2,1]),
 "[2,2,2,12]": prod([0,1], [-120**2,1], [-143**2,1], [-266**2,1], [-218**2,1],
                    [-241**2,1]),
 "[2,2,2,10]": prod([0,1], [1,1], [-1,1], [-7,3], [-13,8], [25,24]),
}
assert set(FACTORED) == set(gen.NEW) | set(gen.LIT_ONLY)

rows = []  # (invariants, [f, h], provenance-comment)
def inv(g):
    if g == "[]":
        return []
    return [int(t) for t in g.strip("[]").split(",")]

for g, (label, fh) in gen.WWW.items():
    rows.append((inv(g), fh, label))
for g, (label, fh) in gen.ALPHA.items():
    rows.append((inv(g), fh, label + " alpha"))
for g, (label, fh) in gen.ALPHA_RM.items():
    rows.append((inv(g), fh, label + " alpha, RM"))
for g, fh in gen.NEW_RM.items():
    rows.append((inv(g), fh, "new: 1830.2.a.q, RM"))
for g in gen.NEW:
    rows.append((inv(g), [FACTORED[g], [0]], "new (this paper)"))
for g in gen.LIT_ONLY:
    rows.append((inv(g), [FACTORED[g], [0]], "Elkies 2024"))

def cost(row):
    return sum(len(str(abs(c))) for c in row[1][0] + row[1][1])
rows.sort(key=cost)

hdr = f"""// verify_simple_torsion_table.m -- verifies the exact torsion subgroup of
// every curve in Table 1 (tab:census) of the paper = the table of torsion
// subgroups realized on geometrically simple genus-2 Jacobians /Q
// (paper/torsion_realizations.tex).
// Generated by code/claude_gen_simple_table_check.py; run from this directory:
//   magma -b verify_simple_torsion_table.m
// Torsion only: geometric simplicity / endomorphism claims are certified
// separately (LMFDB for database rows; data/claude_endz_certificates.txt and
// data/claude_z31_rm_certificate.txt for the non-database rows).
SetColumns(0);
SetMemoryLimit(8*10^9);
R<x> := PolynomialRing(Rationals());

procedure CheckTorsion(I, fh)
    assert I eq Invariants(AbelianGroup(TorsionSubgroup(Jacobian(
        SimplifiedModel(HyperellipticCurve(R!fh[1], R!fh[2]))))));
end procedure;

t0 := Cputime();
n := 0;
"""

lines = [hdr]
for I, fh, com in rows:
    f, h = fh
    lines.append('printf "checking %-14o  (' + com + ')\\n", ' + str(I) + ";\n")
    lines.append(f"CheckTorsion({I}, [{f}, {h}]);\n")
    lines.append("n +:= 1;\n")
lines.append(f"assert n eq {len(rows)};\n")
lines.append('printf "ALL %o CHECKS PASSED (%.1o s)\\n", n, Cputime()-t0;\n')
lines.append("quit;\n")

with open(OUT, "w") as fp:
    fp.write("".join(lines))
print(f"wrote {OUT}: {len(rows)} checks")

# ---------------------------------------------------------------------------
# Also emit verify_simple_certificates.m: geometric-simplicity certificates
# for all 72 witnesses, End(Jac_Qbar) = Z certificates for the new generic
# rows and the Elkies [2,2,2,10] member, and RM evidence for [31] / [2,22].
# ---------------------------------------------------------------------------
OUT2 = os.path.join(ROOT, "paper", "scripts_and_data",
                    "verify_simple_certificates.m")

def flag(com):
    if "RM" in com:
        return 2
    if com in ("new (this paper)", "Elkies 2024"):
        return 1
    return 0

datalines = []
for I, fh, com in rows:
    f, h = fh
    datalines.append(f"  <{I}, {f}, {h}, {flag(com)}, \"{com}\">")
data = "rows := [\n" + ",\n".join(datalines) + "\n];\n"

hdr2 = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                         "claude_simple_certificates_template.m")).read()
with open(OUT2, "w") as fp:
    fp.write(hdr2.replace("//<<DATA>>", data))
print(f"wrote {OUT2}: {len(rows)} curves")
