// verify_split_certificates.m -- geometric splitness certificates for ALL
// 76 rows of Table 2 (tab:splitcensus) of the paper.  Generated by
// code/claude_gen_split_table_check.py from the same witness data as the
// table; run from this directory:
//   magma -b verify_split_certificates.m
//
// Routes (established once by an exploration over the (2,2)-isogeny graph):
//  R1: RichelotIsogenousSurfaces(Jac) over Q contains a DEGENERATE codomain
//      -- either a product E x E' of elliptic curves over Q (SetCart; the
//      conductors are printed) or an elliptic curve over a quadratic field
//      K (CrvEll; the codomain is then E x E^sigma over K).  Either way Jac
//      admits an explicit (2,2)-isogeny to a product over a number field,
//      so it is geometrically split.  58 of the 76 rows certify this way
//      (56 over Q, 2 more over Q(sqrt 2) at depth <= 2: route Q2).
//  COVER: ALL 18 odd-glued curves carry an EXPLICIT nonconstant
//      map phi = (p(x)/q(x), y h(x)/q(x)^2) from the genus-2 curve to a
//      genus-1 curve E, over Q (13 rows, E given by its Cremona label) or
//      over an explicitly given number field K of degree 2 or 3 (4 rows,
//      E : v^2 = 4u^3 - g2 u - g3 with g2, g3 in K).  The verification is a
//      single polynomial identity N(p,q)*q = g*h^2 (plus nonvanishing of
//      the Wronskian p q' - p' q and of disc(E)), checked exactly below; a
//      nonconstant morphism C -> E over any field induces a surjection
//      Jac(C) ->> E, so Jac(C) is geometrically split.  The maps were FOUND
//      numerically (period matrices, endomorphism idempotents, Weierstrass-P
//      evaluation, exact rational/algebraic reconstruction), but the
//      certificate is independent of the search: only the identity matters.
//      All 13 rational covers have degree 3; the K-covers have degrees
//      2, 2, 2, 3, 5 -- in particular the [70] curve of Howe maps to 858k1
//      and [19] = J_1(13) is bielliptic over an explicit sextic field.
//  SIG: (retained for completeness; no row currently uses it): no chain of
//      (2,2)-isogenies can reach a product (the products in their isogeny
//      class are odd-isogenous), so no Richelot-style certificate exists.
//      For these we verify the split SIGNATURE: at EVERY good prime
//      p < 200 the Frobenius polynomial fails the root-power simplicity
//      test (chi_p is reducible, or some power pi^n with n <= 12 generates
//      a proper subfield).  A single strict prime would PROVE geometric
//      simplicity (Part A of verify_simple_certificates.m), so for a
//      genuinely split Jacobian this failure occurs at every good prime;
//      note some of these curves (e.g. [19] = J_1(13)) are Q-simple, so
//      chi_p itself is often irreducible -- the power-drop is the geometric
//      fingerprint.  The splitness statement itself is cited: the certified
//      LMFDB/database endomorphism computation (Costa-Mascot-Sijsling-
//      Voight) for database rows, and Howe 2015 (Thm 2.4) for the [70]
//      curve.  (The signature is strong evidence, not a proof: finitely
//      many Frobenius polynomials cannot prove an endomorphism exists.)
SetColumns(0);
SetMemoryLimit(8*10^9);
Q := Rationals(); Z := Integers();
R<x> := PolynomialRing(Q);
Tp<T> := PolynomialRing(Q);
PxQ<X> := PolynomialRing(Q);

// root-power strictness (as in verify_simple_certificates.m)
function IsStrict(chi)
    if Degree(chi) ne 4 or not IsIrreducible(chi) then return false; end if;
    K := NumberField(chi); pi := K.1;
    for n in [2..12] do
        if Degree(MinimalPolynomial(pi^n)) lt 4 then return false; end if;
    end for;
    return true;
end function;

function SplitNode(L)
    for s in L do
        if Type(s) eq SetCart or Type(s) eq CrvEll then return true, s; end if;
    end for;
    return false, 0;
end function;

//<<DATA>>

t0 := Cputime();
nR := 0; nS := 0;
for row in rows do
    I, fc, hc, route, tag, ck := Explode(row);
    C := SimplifiedModel(HyperellipticCurve(R!fc, R!hc));
    if route eq "R1" then
        ok, s := SplitNode(RichelotIsogenousSurfaces(Jacobian(C)));
        assert ok;
        if Type(s) eq SetCart then
            printf "SPLIT %-14o (2,2)-isogenous /Q to E x E', conductors %o, %o  (%o)\n",
                I, Conductor(s[1]), Conductor(s[2]), tag;
        elif Type(BaseRing(s)) eq FldRat then
            printf "SPLIT %-14o (2,2)-isogenous /Q to E x E, E of conductor %o  (%o)\n",
                I, Conductor(s), tag;
        else
            printf "SPLIT %-14o (2,2)-isogenous to E x E^sigma over %o  (%o)\n",
                I, DefiningPolynomial(BaseRing(s)), tag;
        end if;
        nR +:= 1;
    elif route eq "Q2" then
        K := QuadraticField(2);
        JK := Jacobian(SimplifiedModel(HyperellipticCurve(
            PolynomialRing(K)!(4*(R!fc) + (R!hc)^2))));
        L := RichelotIsogenousSurfaces(JK);
        ok, s := SplitNode(L);
        if not ok then
            for u in L do
                if Type(u) eq JacHyp then
                    ok, s := SplitNode(RichelotIsogenousSurfaces(u));
                    if ok then break; end if;
                end if;
            end for;
        end if;
        assert ok;
        printf "SPLIT %-14o (2,2)-route to a product over Q(sqrt 2)  (%o)\n", I, tag;
        nR +:= 1;
    elif route eq "COVER" then
        cv := covers[ck];
        gg := 4*(R!fc) + (R!hc)^2;
        pv := cv[4]; qv := cv[5]; hv := cv[6];
        assert pv*Derivative(qv) - Derivative(pv)*qv ne 0;   // nonconstant
        if cv[1] eq "Q" then
            Ew := WeierstrassModel(EllipticCurve(CremonaDatabase(), cv[2]));
            WW := HyperellipticPolynomials(Ew);
            NN := pv^3 + Coefficient(WW,2)*pv^2*qv
                + Coefficient(WW,1)*pv*qv^2 + Coefficient(WW,0)*qv^3;
            assert NN*qv eq gg*hv^2;
            printf "SPLIT %-14o degree-%o map to elliptic curve %o over Q  (%o)\n",
                I, cv[3], cv[2], tag;
        else
            dat := coverK[ck];
            Kf := dat[1]; g2K := dat[2]; g3K := dat[3];
            assert g2K^3 - 27*g3K^2 ne 0;                    // E nonsingular
            NN := 4*pv^3 - g2K*pv*qv^2 - g3K*qv^3;
            PKl := Parent(pv);
            assert NN*qv eq (PKl!gg)*hv^2;
            printf "SPLIT %-14o degree-%o map to an elliptic curve over a degree-%o field  (%o)\n",
                I, cv[3], Degree(Kf), tag;
        end if;
        nR +:= 1;
    else // SIG
        g0 := 4*(R!fc) + (R!hc)^2;
        d0 := LCM([Z | Denominator(c) : c in Coefficients(g0)]);
        g := R!(d0^2*g0);
        D := Z!Discriminant(g);
        n := 0;
        for p in PrimesInInterval(3, 200) do
            if D mod p eq 0 or (Z!LeadingCoefficient(g)) mod p eq 0 then
                continue;
            end if;
            gp := PolynomialRing(GF(p))!g;
            if Degree(gp) lt 5 or not IsSquarefree(gp) then continue; end if;
            chi := Tp!Reverse(Coefficients(
                EulerFactor(Jacobian(HyperellipticCurve(gp)))));
            assert not IsStrict(chi);
            n +:= 1;
        end for;
        printf "SIG   %-14o odd gluing: no strict prime among %o good p<200; splitness cited  (%o)\n",
            I, n, tag;
        nS +:= 1;
    end if;
end for;
assert nR + nS eq #rows;
printf "ALL %o SPLITNESS CHECKS PASSED: %o by explicit isogeny or cover, %o signature+citation (%.1o s)\n",
    #rows, nR, nS, Cputime() - t0;
quit;
