//////////////////////////////////////////////////////////////////////
// claude_ov_m612ap_relq.m       lane 9 ([6,12])   2026-07-25
//
// The mod-q sieve data (results/ap2, results/ap3) show, at EVERY usable
// prime, that
//        ord(W1 mod q) = 1     and     W3 = W2  in J(E8)(F_q).
// This script tries to prove both relations over Q directly, by testing
// whether the degree-0 divisors
//        D1 := P_{g1} - P_{g1(-y)}                 (should be principal)
//        D23:= (P_{g2}-P_{g2(-y)}) - (P_{g3}-P_{g3(-y)})   (ditto)
// are principal on the genus-4 function field E8 over Q.  A degree-0
// divisor D is principal iff dim L(D) = 1 (and then L(D) = <h> with
// div(h) = -D up to sign).
//
// If this succeeds, Lambda = <W1,W2,W3> = <W2> is CYCLIC, generated by one
// explicit class, and the Abel-Prym sieve is a genuine one-generator MW
// sieve rather than a sieve on an unknown-rank subgroup.
//
// Usage: code/claude_magma_slot.sh -b code/claude_ov_m612ap_relq.m
//////////////////////////////////////////////////////////////////////

SetColumns(0);
if not assigned memgb then memgb := 12; elif Type(memgb) eq MonStgElt then memgb := StringToInteger(memgb); end if;
SetMemoryLimit(memgb*10^9);

QQ := Rationals();
Fx<X> := RationalFunctionField(QQ);
Py<Y> := PolynomialRing(Fx);
Q8 := Y^8 + (216*X^4+72*X^3-24*X^2)*Y^4
    + (-1296*X^6-1728*X^5-432*X^4+64*X^3)*Y^2
    + (-3888*X^8-2592*X^7+432*X^6+288*X^5-48*X^4);
printf "Q8 irreducible: %o\n", IsIrreducible(Q8);
F<yy> := FunctionField(Q8);
printf "genus: %o\n", Genus(F);

Pt<t> := PolynomialRing(QQ);
GENS := [
  < QQ!(-2)/3,  t^3 - 2*t^2 + (QQ!4/3)*t + QQ!8/3 >,
  < QQ!(-2)/5,  t^3 - (QQ!6/5)*t^2 + (QQ!12/25)*t - QQ!152/125 >,
  < QQ!(2)/15,  t^3 - (QQ!2/5)*t^2 + (QQ!4/75)*t - QQ!88/375 >
];

// build P_g and P_{g(-y)} as divisors on F
mkpair := function(x0, g)
  gm := Evaluate(g, -t);
  zx := Zeros(Fx.1 - x0)[1];
  dec := Decomposition(F, zx);
  dec := [ Type(D) eq Tup select D[1] else D : D in dec ];
  Dp := DivisorGroup(F)!0; Dm := DivisorGroup(F)!0; dp := 0; dm := 0;
  for P in dec do
    RF := ResidueClassField(P);
    rr := Evaluate(yy, P);
    vp := &+[ (RF!Coefficient(g ,i)) * rr^i : i in [0..Degree(g )] ];
    vm := &+[ (RF!Coefficient(gm,i)) * rr^i : i in [0..Degree(gm)] ];
    if vp eq 0 then Dp +:= Divisor(P); dp +:= Degree(P); end if;
    if vm eq 0 then Dm +:= Divisor(P); dm +:= Degree(P); end if;
  end for;
  return Dp, Dm, dp, dm;
end function;

Ds := [];
for i in [1..#GENS] do
  Dp, Dm, dp, dm := mkpair(GENS[i][1], GENS[i][2]);
  printf "generator %o : deg(P_g) = %o, deg(P_g(-y)) = %o\n", i, dp, dm;
  error if dp ne 3 or dm ne 3, "bad degrees over Q";
  Append(~Ds, Dp - Dm);
end for;

test := procedure(name, D)
  printf "--- %o : degree %o\n", name, Degree(D);
  ok := true; pr := false; hh := 0;
  try
    pr, hh := IsPrincipal(D);
  catch err
    ok := false;
    printf "    IsPrincipal failed (%o); falling back to RiemannRochSpace\n", err`Object;
  end try;
  if ok then
    printf "    IsPrincipal: %o\n", pr;
    if pr then printf "    generator: %o\n", hh; end if;
    return;
  end if;
  V, mV := RiemannRochSpace(D);
  printf "    dim L(D) = %o  (principal iff 1 for a degree-0 divisor)\n", Dimension(V);
  if Dimension(V) ge 1 then
    printf "    a function: %o\n", mV(V.1);
  end if;
end procedure;

test("D1  = W1", Ds[1]);
test("D23 = W2 - W3", Ds[2] - Ds[3]);
test("D2  = W2 (control, expected NOT principal)", Ds[2]);

print "AP_RELQ_DONE";
quit;
