#!/usr/bin/env python3
"""Mechanical C-table generator for code/claude_z31_kummer_sieve.c.

Reads flynn_polys.json (produced by the Flynn-file parser flynn_parse.py from
https://people.maths.ox.ac.uk/flynn/genus2/kummer/{duplication,defining.equations,
biquadratic.forms}) and emits claude_z31_kummer_tables.h containing:
  - eval_fmons(): straight-line evaluation of all distinct f-monomials
  - eval_kmon4()/eval_kmon2(): straight-line k-monomial evaluation
  - term tables for delta1..4, kummeqn, BBB[1,1],BBB[2,1],BBB[3,1],BBB[4,1]
Fidelity: purely mechanical — monomial lists and coefficient tables are emitted
directly from the parsed exact polynomials; no hand-retyping anywhere.  The C
transcription is verified against the Python reference evaluator on random
tuples (polytest mode) and against B1's Magma vectors (selftest mode).
"""
import json, sys

sdir = sys.argv[1] if len(sys.argv) > 1 else '.'
J = json.load(open(f'{sdir}/flynn_polys.json'))
VARS = J['vars']

NAMES3 = ['delta1', 'delta2', 'delta3', 'delta4', 'kummeqn']
NAMES4 = ['BBB[1,1]', 'BBB[2,1]', 'BBB[3,1]', 'BBB[4,1]']
CID = {'delta1': 'DELTA1', 'delta2': 'DELTA2', 'delta3': 'DELTA3',
       'delta4': 'DELTA4', 'kummeqn': 'KUMMEQN', 'BBB[1,1]': 'BB11',
       'BBB[2,1]': 'BB21', 'BBB[3,1]': 'BB31', 'BBB[4,1]': 'BB41'}

def split_exp(e):
    return tuple(e[0:7]), tuple(e[7:11]), tuple(e[11:15])

# collect distinct monomials
fmons, kmons4, kmons2 = {}, {}, {}
maxc = 0
for nm in NAMES3 + NAMES4:
    for e, c in J['polys'][nm]:
        fe, ke, le = split_exp(e)
        maxc = max(maxc, abs(c))
        fmons.setdefault(fe, len(fmons))
        if nm in NAMES3:
            assert sum(le) == 0
            assert sum(ke) == 4
            kmons4.setdefault(ke, len(kmons4))
        else:
            assert sum(ke) == 2 and sum(le) == 2
            kmons2.setdefault(ke, len(kmons2))
            kmons2.setdefault(le, len(kmons2))

fm_list = sorted(fmons, key=lambda e: (sum(e), e))
k4_list = sorted(kmons4)
k2_list = sorted(kmons2)
fm_idx = {e: i for i, e in enumerate(fm_list)}
k4_idx = {e: i for i, e in enumerate(k4_list)}
k2_idx = {e: i for i, e in enumerate(k2_list)}

out = []
out.append('/* AUTO-GENERATED by code/claude_z31_gen_tables.py — DO NOT EDIT.')
out.append(' * Source: Flynn kummer files (duplication, defining.equations,')
out.append(' * biquadratic.forms) parsed to exact integer polynomials.')
out.append(f' * max |coeff| = {maxc} (must be < every sieve prime). */')
out.append(f'#define NFMON {len(fm_list)}')
out.append(f'#define NKMON4 {len(k4_list)}')
out.append(f'#define NKMON2 {len(k2_list)}')
out.append(f'#define MAXCOEFF {maxc}')
out.append('typedef struct { int16_t c; uint16_t fi, ki; } Term3;')
out.append('typedef struct { int16_t c; uint16_t fi, ki, li; } Term4;')

def emit_mono_eval(name, mlist, base, nbase):
    """straight-line code: out[i] = product of base vars with given exponents"""
    out.append(f'static void {name}(Mod *M, u32 *{base}, u32 *out)')
    out.append('{')
    out.append('    (void)M;')
    for i, e in enumerate(mlist):
        facs = []
        for vi, ei in enumerate(e):
            facs += [f'{base}[{vi}]'] * ei
        if not facs:
            out.append(f'    out[{i}] = 1;')
        else:
            expr = facs[0]
            for f2 in facs[1:]:
                expr = f'mmul(M, {expr}, {f2})'
            out.append(f'    out[{i}] = {expr};')
    out.append('}')

emit_mono_eval('eval_fmons', fm_list, 'f', 7)
emit_mono_eval('eval_kmon4', k4_list, 'x', 4)
emit_mono_eval('eval_kmon2', k2_list, 'x', 4)

for nm in NAMES3:
    terms = []
    for e, c in J['polys'][nm]:
        fe, ke, le = split_exp(e)
        terms.append((c, fm_idx[fe], k4_idx[ke]))
    terms.sort(key=lambda t: (t[2], t[1]))
    out.append(f'#define N_{CID[nm]} {len(terms)}')
    out.append(f'static Term3 {CID[nm]}_T[] = {{')
    out.append('    ' + ','.join(f'{{{c},{fi},{ki}}}' for c, fi, ki in terms))
    out.append('};')

for nm in NAMES4:
    terms = []
    for e, c in J['polys'][nm]:
        fe, ke, le = split_exp(e)
        terms.append((c, fm_idx[fe], k2_idx[ke], k2_idx[le]))
    terms.sort(key=lambda t: (t[2], t[3], t[1]))
    out.append(f'#define N_{CID[nm]} {len(terms)}')
    out.append(f'static Term4 {CID[nm]}_T[] = {{')
    out.append('    ' + ','.join(f'{{{c},{fi},{ki},{li}}}' for c, fi, ki, li in terms))
    out.append('};')

path = sys.argv[2] if len(sys.argv) > 2 else 'claude_z31_kummer_tables.h'
open(path, 'w').write('\n'.join(out) + '\n')
print(f'wrote {path}: NFMON={len(fm_list)} NKMON4={len(k4_list)} '
      f'NKMON2={len(k2_list)} maxcoeff={maxc}')
for nm in NAMES3 + NAMES4:
    print(f'  {nm}: {len(J["polys"][nm])} terms')
