// ===========================================================================
// Lane 2 (claude_ov_c7z) -- HARDEN the Chabauty proof and describe X.
//   (a) rank(Jac H) = 1 exactly, generator saturated at all small primes
//   (b) meaning / value of the second return of Chabauty
//   (c) the 13 rational points of X listed explicitly
//   (d) Aut(X) and Aut(H); is Jac(H) simple?
// ===========================================================================
SetColumns(0);
if not assigned MemGB then MemGB := 16; elif Type(MemGB) eq MonStgElt then MemGB := StringToInteger(MemGB); end if;
SetMemoryLimit(MemGB*10^9);
Q := Rationals();
PP<X> := PolynomialRing(Q);
G1 := X*(X-3)*(X^2-24*X+36);
G2 := (X-3)*(7*X-12)*(37*X^2-96*X+36);
GH := X*(7*X-12)*(X^2-24*X+36)*(37*X^2-96*X+36);
CH := HyperellipticCurve(GH);
JH := Jacobian(CH);

// (b) Magma handbook, Chabauty(P : ptC) : JacHypPt -> SetIndx :
//   "returns the set of points on C whose images in J(Q) lie in the SATURATION in
//    J(Q) of the group generated by P.  In particular when J(Q) has rank 1, all
//    rational points on C are returned."
// So the saturation is handled internally; we only need rank(J(Q)) = 1, which is
// proved by RankBounds = 0..1 together with an exhibited point of infinite order.

printf "\n==== (a) rank and saturation ====\n";
lo, hi := RankBounds(JH);
printf "RankBounds = %o..%o\n", lo, hi;
ptsH := Points(CH : Bound := 200000);
JPts := [];
for i in [1..#ptsH], j in [1..#ptsH] do
  if i eq j then continue; end if;
  ok := true; D := JH!0;
  try D := JH ! [ptsH[i], ptsH[j]]; catch e ok := false; end try;
  if ok then Append(~JPts, D); end if;
end for;
bas := ReducedBasis(JPts);
printf "ReducedBasis: %o gen(s); heights %o\n", #bas, [Height(b) : b in bas];
assert #bas eq 1;
P := bas[1];
printf "P = %o  hhat(P) = %o\n", P, Height(P);
sat := bas;
for p in PrimesUpTo(50) do
  ok := true;
  try
    ns := Saturation(sat, p);
    if ns ne sat then printf "  p=%o : SATURATION ENLARGED -> %o\n", p, ns; end if;
    sat := ns;
  catch e
    ok := false; printf "  p=%o : Saturation error %o\n", p, e`Object;
  end try;
end for;
printf "after saturation at all primes <= 50: gens %o heights %o\n", sat, [Height(b) : b in sat];
printf "index check: hhat(sat gen) = %o vs hhat(P) = %o\n", Height(sat[1]), Height(P);
// independent: search J(Q) for points of small canonical height
hc := HeightConstant(JH : Effort := 2);
printf "HeightConstant(J) = %o  (naive - canonical bound)\n", hc;
smallJ := Points(JH : Bound := 400);
hts := Sort([ Height(D) : D in smallJ | Order(D) eq 0 ]);
printf "#Points(J,Bound:=400) = %o ; smallest infinite-order canonical heights: %o\n",
   #smallJ, hts[1..Min(6,#hts)];

printf "\n==== Chabauty re-run with the saturated generator ====\n";
V, N := Chabauty(sat[1]);
printf "Chabauty: #V = %o, second return = %o (type %o)\n", #V, N, Type(N);
printf "V = %o\n", V;
printf "matches naive Points(Bound:=200000)? %o\n", {p : p in V} eq {p : p in ptsH};

printf "\n==== (c) the rational points of X ====\n";
allX := [];
for tv in [Q| -6, 0, 12/7, 2, 3 ] do
  s1, u := IsSquare(Evaluate(G1,tv));
  s2, v := IsSquare(Evaluate(G2,tv));
  assert s1 and s2;
  us := (u eq 0) select [u] else [u,-u];
  vs := (v eq 0) select [v] else [v,-v];
  for uu in us, vv in vs do Append(~allX, <tv,uu,vv>); end for;
end for;
printf "#X(Q) (affine, T finite) = %o\n", #allX;
for t in allX do printf "   (T,u,v) = (%o, %o, %o)\n", t[1], t[2], t[3]; end for;
printf "points at infinity of X: fibre over T=oo needs sqrt(lc G1)=sqrt(%o) and sqrt(lc G2)=sqrt(%o) -> field Q(sqrt %o), NOT rational\n",
   LeadingCoefficient(G1), LeadingCoefficient(G2), LeadingCoefficient(G2);

printf "\n==== (d) automorphisms and the isogeny type ====\n";
printf "Aut(H) over Q: ";
try
  AH := AutomorphismGroup(CH);
  printf "%o (order %o)\n", AH, #AH;
catch e printf "failed: %o\n", e`Object; end try;
printf "GeometricAutomorphismGroup(H) = %o\n", IdentifyGroup(GeometricAutomorphismGroup(CH));
// is Jac(H) geometrically simple / does it split?
printf "-- Frobenius L-polys of H at good primes (looking for a split) --\n";
nsplit := 0;
for p in PrimesInInterval(5,200) do
  if Integers()!Discriminant(CH) mod p eq 0 then continue; end if;
  Lp := LPolynomial(ChangeRing(CH, GF(p)));
  fa := Factorisation(Lp);
  if #fa gt 1 or fa[1][2] gt 1 then
    nsplit +:= 1;
    if nsplit le 8 then printf "   p=%o : L = %o  (reducible)\n", p, [<f[1],f[2]> : f in fa]; end if;
  end if;
end for;
printf "reducible L-polys among primes 5..200: %o\n", nsplit;

printf "\n-- genus-4 curve X : automorphisms of the function field --\n";
KA := FunctionField(Q); TA := KA.1;
PA<YA> := PolynomialRing(KA);
F1 := FunctionField(YA^2 - Evaluate(G1,TA));
PB<YB> := PolynomialRing(F1);
F2 := FunctionField(YB^2 - (F1!Evaluate(G2,TA)));
printf "genus(X) = %o\n", Genus(F2);
try
  AX := Automorphisms(F2);
  printf "#Automorphisms(X/Q) = %o\n", #AX;
catch e printf "Automorphisms(X/Q) failed: %o\n", e`Object; end try;
printf "VERIFY_DONE\n";
quit;
