//////////////////////////////////////////////////////////////////////
// Exact verifier for the contact-(5,6) order-30 C3-root Richelot route.
//
// A rational root rho of
//
//   C3 = h6 + (x-1)^3
//
// gives the factorization
//
//   f = A0*B0*L,
//   A0 = h6-(x-1)^3, B0 = C3/(x-rho), L = x-rho.
//
// The pointwise-rational Richelot kernel is generated by the three
// nonzero classes [A0,0], [B0,0], [L,0].  With
//
//   U=[B0,L], V=[L,A0], W=[A0,B0],
//   Delta=det(coeff(A0),coeff(B0),coeff(L)),
//
// the distinguished codomain is y^2=Delta*U*V*W.  This script proves
// the generic resultant identities, runs three finite positive controls,
// and verifies a supplied rational root point all the way through exact
// torsion, dual-class divisibility, and geometric simplicity.  The
// resultant tests are necessary, not sufficient.  Dual-isogeny transport
// sharpens the W test: W can halve only when both A0 and B0 split.
//
// Self-tests:
//   magma -b mode:="selftest" \
//     code/contact30_c3root_richelot_verify.m
//
// Rational point in the R-chart:
//   magma -b mode:="rational" R_num:=... R_den:=... branch:=... \
//     rho_num:=... rho_den:=... \
//     code/contact30_c3root_richelot_verify.m
//
// Rational point in compact (u,s)-coordinates:
//   magma -b mode:="rational" u_num:=... u_den:=... \
//     s_num:=... s_den:=... rho_num:=... rho_den:=... \
//     code/contact30_c3root_richelot_verify.m
//////////////////////////////////////////////////////////////////////

SetColumns(0);

if not assigned mode then mode := "selftest"; end if;
if mode notin {"selftest", "rational"} then
    error "mode must be selftest or rational";
end if;
if not assigned solve_affine_halves then
    solve_affine_halves := false;
elif Type(solve_affine_halves) eq MonStgElt then
    solve_affine_halves := solve_affine_halves in {"true","True","1","yes"};
end if;
if not assigned print_halving_equations then
    print_halving_equations := false;
elif Type(print_halving_equations) eq MonStgElt then
    print_halving_equations :=
        print_halving_equations in {"true","True","1","yes"};
end if;

Q := Rationals();
Z := Integers();
P<x> := PolynomialRing(Q);
PT<Tfrob> := PolynomialRing(Q);

function AsInteger(a)
    return Type(a) eq MonStgElt select StringToInteger(a) else Z!a;
end function;

function MakeMonic(a)
    return a/LeadingCoefficient(a);
end function;

function Bracket(a,b)
    return Derivative(a)*b-a*Derivative(b);
end function;

function CoefficientMatrixDeterminant(a,b,c)
    F := BaseRing(Parent(a));
    M := Matrix(F,3,3,
        [Coefficient(a,i):i in [0..2]] cat
        [Coefficient(b,i):i in [0..2]] cat
        [Coefficient(c,i):i in [0..2]]);
    return Determinant(M);
end function;

function GoodGenus2Polynomial(f)
    return Degree(f) in {5,6} and Discriminant(f) ne 0;
end function;

function GroupExponent(inv)
    e := Z!1;
    for n in inv do e := LCM(e,Z!n); end for;
    return e;
end function;

function GroupOrder(inv)
    return #inv eq 0 select Z!1 else &*[Z!n:n in inv];
end function;

function IntegralSquareModel(f)
    d := Z!1;
    for i in [0..Degree(f)] do
        d := LCM(d,Denominator(Coefficient(f,i)));
    end for;
    return P!(d^2*f),d;
end function;

//////////////////////////////////////////////////////////////////////
// Contact family reconstruction.
//////////////////////////////////////////////////////////////////////

function ContactDataFromUS(u,s)
    F := Parent(u);
    PP<X> := PolynomialRing(F);
    z := PP.1;
    if u eq 0 then return false,[* *]; end if;
    Cc := (u^2+1)/(2*u);
    c := (u^2-1)/(2*u);
    denq := u^6+6*u^4*s-2*u^4+15*u^3*s-u*s^3+u^2;
    if c eq 0 or denq eq 0 then return false,[* *]; end if;
    numq := 15*u^5+90*u^4+20*u^3*s-6*u^2*s^2+231*u^3
        +2*u^2*s-15*u*s^2+90*u^2-20*u*s+15*u-2*s;
    q := numq/denq;
    aa := (s+q)/2;
    ee := (s-q)/2;
    bb := (15-s*q)/2;
    dd := (bb*Cc+3)/c;
    h6 := z^3+aa*z^2+bb*z+Cc;
    h5 := ee*z^2+dd*z+c;
    f := h6^2-(z-1)^6;
    Kcontact := ExactQuotient(h5^2-f,z^5);
    A0 := h6-(z-1)^3;
    C3 := h6+(z-1)^3;
    return true,[* u,s,q,aa,bb,Cc,c,ee,dd,h6,h5,f,Kcontact,A0,C3 *];
end function;

function ContactDataFromR(rpar,branch)
    F := Parent(rpar);
    den := rpar^2-5;
    if den eq 0 then return false,[* *]; end if;
    t := (5*rpar^2-20*rpar+19)/den;
    YY := -2*(5*rpar^2-22*rpar+25)/den;
    u := t^3;
    s := t^5+t^4+(F!5/2)*t^3+(F!1/2)*t
        +(F!branch)*t*(t-F!1/2)*(t+1)*YY;
    ok,data := ContactDataFromUS(u,s);
    if not ok then return false,[* *]; end if;
    return true,[* rpar,F!branch,t,YY *] cat data;
end function;

function RichelotData(A0,C3,rho)
    PP := Parent(A0);
    z := PP.1;
    L := z-rho;
    if Evaluate(C3,rho) ne 0 then return false,[* *]; end if;
    B0 := ExactQuotient(C3,L);
    if Degree(A0) ne 2 or Degree(B0) ne 2 then
        return false,[* *];
    end if;
    Delta := CoefficientMatrixDeterminant(A0,B0,L);
    if Delta eq 0 then return false,[* *]; end if;
    U := Bracket(B0,L);
    V := Bracket(L,A0);
    W := Bracket(A0,B0);
    g := Delta*U*V*W;
    if not GoodGenus2Polynomial(g) then return false,[* *]; end if;
    return true,[* A0,B0,L,Delta,U,V,W,g *];
end function;

//////////////////////////////////////////////////////////////////////
// Exact affine Mumford halving equations.
//
// For T=[u,0], put ell=u*(M*x+N) and
//
//   S=(ell^2-f)/u.
//
// On the ordinary degree-4 residual chart, T is halved precisely when
// S is a scalar times a square quadratic.  E1=E0=0 is that condition.
// IsDivisibleBy below remains the definitive chart-independent check.
//////////////////////////////////////////////////////////////////////

function SquareQuarticEquations(S)
    s4 := Coefficient(S,4); s3 := Coefficient(S,3);
    s2 := Coefficient(S,2); s1 := Coefficient(S,1);
    s0 := Coefficient(S,0);
    E1 := 8*s4^2*s1-s3*(4*s4*s2-s3^2);
    E0 := 64*s4^3*s0-(4*s4*s2-s3^2)^2;
    return E1,E0;
end function;

function SquareQuarticData(S)
    if Degree(S) ne 4 then return false,Q!0,P!0; end if;
    s4 := Coefficient(S,4);
    if s4 eq 0 then return false,Q!0,P!0; end if;
    s3 := Coefficient(S,3); s2 := Coefficient(S,2);
    G := x^2+(s3/(2*s4))*x+(4*s4*s2-s3^2)/(8*s4^2);
    return S eq s4*G^2,Q!s4,P!G;
end function;

function HalvingEquations(u,f)
    S<M,N> := PolynomialRing(Q,2);
    SX<X> := PolynomialRing(S);
    emb := hom<P->SX|X>;
    uX := emb(u); fX := emb(f);
    ell := uX*(M*X+N);
    assert (ell^2-fX) mod uX eq 0;
    residual := ExactQuotient(ell^2-fX,uX);
    E1,E0 := SquareQuarticEquations(residual);
    return S!E1,S!E0;
end function;

function AffineHalves(u,f)
    S<M,N> := PolynomialRing(Q,2);
    SX<X> := PolynomialRing(S);
    emb := hom<P->SX|X>;
    uX := emb(u); fX := emb(f);
    ell := uX*(M*X+N);
    residual := ExactQuotient(ell^2-fX,uX);
    E1,E0 := SquareQuarticEquations(residual);
    pts := [];
    try pts := Variety(ideal<S|E1,E0>); catch e return [* *]; end try;
    out := [* *];
    for pt in pts do
        m := Q!pt[1]; n := Q!pt[2];
        ellq := u*(m*x+n);
        Sq := ExactQuotient(ellq^2-f,u);
        ok,lambda,G := SquareQuarticData(Sq);
        if ok then Append(~out,<m,n,G,ellq,lambda>); end if;
    end for;
    return out;
end function;

//////////////////////////////////////////////////////////////////////
// Finite and rational certification helpers.
//////////////////////////////////////////////////////////////////////

function IsDoubleFinite(J,D)
    G,phi := AbelianGroup(J);
    d := D @@ phi;
    twice := sub<G|[2*G.i:i in [1..Ngens(G)]]>;
    return d in twice,Invariants(G);
end function;

function FrobeniusPolynomial(C,p)
    ef := EulerFactor(C,p); d := Degree(ef);
    return &+[Q!Coefficient(ef,i)*Tfrob^(d-i):i in [0..d]];
end function;

function FullSimplicityCertificate(f)
    C := HyperellipticCurve(f);
    plist := [p:p in PrimesUpTo(199)|p ge 3];
    for p in plist do
        try
            Phi := FrobeniusPolynomial(C,p);
            fac := Factorization(Phi);
            if #fac ne 1 or fac[1][2] ne 1 or Degree(fac[1][1]) ne 4 then
                continue;
            end if;
            Gal := GaloisGroup(Phi); desc := "unknown";
            try
                desc := TransitiveGroupDescription(Gal);
            catch e2
                desc := "unknown";
            end try;
            if Order(Gal) eq 8 and desc eq "D(4)" then
                return true,"D4",p,Phi;
            end if;
        catch e
            dummy := 0;
        end try;
    end for;
    for p in plist do
        try
            Phi := FrobeniusPolynomial(C,p);
            fac := Factorization(Phi);
            if #fac ne 1 or fac[1][2] ne 1 or Degree(fac[1][1]) ne 4 then
                continue;
            end if;
            K<pi> := NumberField(Phi);
            if &and[Degree(MinimalPolynomial(pi^n)) eq 4:n in [2..12]] then
                return true,"root_power",p,Phi;
            end if;
        catch e
            dummy := 0;
        end try;
    end for;
    return false,"none",0,PT!0;
end function;

function PointOfExactOrder(G,phi,n)
    for i in [1..Ngens(G)] do
        ord := Order(G.i);
        if ord mod n eq 0 then
            a := (ord div n)*G.i;
            D := phi(a);
            if Order(D) eq n then return true,D,a; end if;
        end if;
    end for;
    return false,_,_;
end function;

procedure SymbolicResultantProof()
    S<a2,a1,a0,b2,b1,b0,r> := PolynomialRing(Q,7);
    SX<X> := PolynomialRing(S);
    A := a2*X^2+a1*X+a0;
    B := b2*X^2+b1*X+b0;
    L := X-r;
    U := Derivative(B)*L-B;
    V := A-L*Derivative(A);
    W := Derivative(A)*B-A*Derivative(B);
    M := Matrix(S,3,3,
        [Coefficient(A,i):i in [0..2]] cat
        [Coefficient(B,i):i in [0..2]] cat
        [Coefficient(L,i):i in [0..2]]);
    Delta := Determinant(M);
    assert U eq b2*X^2-2*b2*r*X-b1*r-b0;
    assert V eq -a2*X^2+2*a2*r*X+a1*r+a0;
    assert W eq (a2*b1-a1*b2)*X^2
        +(2*a2*b0-2*a0*b2)*X+a1*b0-a0*b1;
    assert Delta eq a2*b1*r+a2*b0-a1*b2*r-a0*b2;
    assert Delta eq a2*Evaluate(B,r)-b2*Evaluate(A,r);
    assert Resultant(U,V) eq Delta^2;
    assert Resultant(U,W) eq Delta^2*Discriminant(B);
    assert Resultant(V,W) eq Delta^2*Discriminant(A);
    print "SYMBOLIC_RESULTANTS_OK";
    print "Res(U,V)=Delta^2";
    print "Res(U,W)=Delta^2*disc(B0)";
    print "Res(V,W)=Delta^2*disc(A0)";
end procedure;

procedure FiniteControl(p,rint,branch,rhoint,expected_inv,expected_halves)
    F := GF(p); PF<z> := PolynomialRing(F);
    ok,data := ContactDataFromR(F!rint,branch);
    assert ok;
    // R-data are followed by the 15 entries returned by ContactDataFromUS.
    h6 := PF!data[14]; h5 := PF!data[15]; f := PF!data[16];
    A0 := PF!data[18]; C3 := PF!data[19];
    rho := F!rhoint;
    assert Evaluate(C3,rho) eq 0;
    rok,rd := RichelotData(A0,C3,rho);
    assert rok;
    B0 := PF!rd[2]; L := PF!rd[3];
    U := PF!rd[5]; V := PF!rd[6]; W := PF!rd[7]; g := PF!rd[8];
    Js := Jacobian(HyperellipticCurve(f));
    Gsource,phisource := AbelianGroup(Js);
    source_inv := Invariants(Gsource);
    source_factor_degrees := Sort([Degree(ff[1]):ff in Factorization(f)]);
    D5 := Js![z,Evaluate(h5,0)];
    D6 := Js![z-1,Evaluate(h6,1)];
    assert Order(D5) eq 5 and Order(D6) eq 6 and Order(D5+D6) eq 30;
    TA := Js![MakeMonic(A0),F!0];
    TB := Js![MakeMonic(B0),F!0];
    TL := Js![L,F!0];
    assert TA+TB+TL eq Js!0 and 3*D6 eq TA;
    Jd := Jacobian(HyperellipticCurve(g));
    assert #Js eq #Jd;
    dual_classes := [Jd![MakeMonic(R),F!0]:R in [U,V,W]];
    assert &+dual_classes eq Jd!0;
    halves := [];
    inv := [];
    for T2 in dual_classes do
        isdouble,inv0 := IsDoubleFinite(Jd,T2);
        Append(~halves,isdouble); inv := inv0;
    end for;
    dA := Discriminant(A0); dB := Discriminant(B0);
    norm_gates := [IsSquare(dB),IsSquare(dA),IsSquare(dA*dB)];
    split_gates := [IsSquare(dB),IsSquare(dA),
                    IsSquare(dA) and IsSquare(dB)];
    assert &and[not halves[i] or split_gates[i]:i in [1..3]];
    assert halves eq expected_halves and inv eq expected_inv;
    assert GroupExponent(inv) mod 60 eq 0;
    print "FINITE_CONTROL",p,"R",rint,"branch",branch,"rho",rhoint,
        "source_order",#Js,"source",source_inv,
        "source_factor_degrees",source_factor_degrees,
        "dual",inv,"halves_UVW",halves,
        "norm_gates",norm_gates,"split_gates",split_gates;
end procedure;

procedure RationalMumfordPositiveControl()
    A0 := x^2+5*x+6; B0 := x^2+x-3; L := x-1;
    Delta := CoefficientMatrixDeterminant(A0,B0,L);
    U := Bracket(B0,L); V := Bracket(L,A0); W := Bracket(A0,B0);
    g := Delta*U*V*W;
    J := Jacobian(HyperellipticCurve(g));
    classes := [J![MakeMonic(R),Q!0]:R in [U,V,W]];
    halves := [];
    for T2 in classes do Append(~halves,IsDivisibleBy(T2,2)); end for;
    assert halves eq [false,true,false];
    candidates := AffineHalves(MakeMonic(V),g);
    assert #candidates eq 4;
    for h in candidates do
        H := J![h[3],-h[4] mod h[3]];
        assert 2*H eq classes[2] and Order(H) eq 4;
    end for;
    G,phi := TorsionSubgroup(J);
    assert Invariants(G) eq [2,4];
    print "RATIONAL_MUMFORD_CONTROL", "Delta",Delta,"torsion",Invariants(G),
        "halves_UVW",halves,"affine_halves_of_V",#candidates;
end procedure;

procedure VerifyRationalPoint(data,rho,chart_label)
    // Locate the common 15-entry tail in either input chart.
    offset := chart_label eq "R" select 4 else 0;
    u := Q!data[offset+1]; s := Q!data[offset+2]; q := Q!data[offset+3];
    aa := Q!data[offset+4]; bb := Q!data[offset+5]; Cc := Q!data[offset+6];
    c := Q!data[offset+7]; ee := Q!data[offset+8]; dd := Q!data[offset+9];
    h6 := P!data[offset+10]; h5 := P!data[offset+11]; f := P!data[offset+12];
    Kcontact := Q!data[offset+13]; A0 := P!data[offset+14]; C3 := P!data[offset+15];

    assert h6^2-(x-1)^6 eq f;
    assert h5^2-Kcontact*x^5 eq f;
    if Evaluate(C3,rho) ne 0 then
        print "ROOT_CHECK_FAILED", "C3(rho)",Evaluate(C3,rho);
        return;
    end if;
    rok,rd := RichelotData(A0,C3,rho);
    if not rok then
        print "RICHELOT_BOUNDARY", "rho",rho;
        return;
    end if;
    B0 := P!rd[2]; L := P!rd[3]; Delta := Q!rd[4];
    U := P!rd[5]; V := P!rd[6]; W := P!rd[7]; g := P!rd[8];

    assert f eq A0*B0*L;
    assert Resultant(U,V) eq Delta^2;
    assert Resultant(U,W) eq Delta^2*Discriminant(B0);
    assert Resultant(V,W) eq Delta^2*Discriminant(A0);

    fI,scaleS := IntegralSquareModel(f);
    gI,scaleD := IntegralSquareModel(g);
    Js := Jacobian(HyperellipticCurve(fI));
    D5 := Js![x,scaleS*Evaluate(h5,0)];
    D6 := Js![x-1,scaleS*Evaluate(h6,1)];
    ords := [Order(D5),Order(D6),Order(D5+D6)];
    assert ords eq [5,6,30];
    P15 := 2*(D5+D6);
    assert Order(P15) eq 15;
    TA := Js![MakeMonic(A0),Q!0];
    TB := Js![MakeMonic(B0),Q!0];
    TL := Js![L,Q!0];
    assert &and[Order(T2) eq 2:T2 in [TA,TB,TL]];
    assert TA+TB+TL eq Js!0;
    assert 3*D6 eq TA and 15*(D5+D6) eq TA;

    Gs,phis := TorsionSubgroup(Js);
    invS := Invariants(Gs);
    Jd := Jacobian(HyperellipticCurve(gI));
    dual_factors := [U,V,W];
    dual_classes := [Jd![MakeMonic(R),Q!0]:R in dual_factors];
    assert &and[Order(T2) eq 2:T2 in dual_classes];
    assert &+dual_classes eq Jd!0;

    dA := Q!Discriminant(A0); dB := Q!Discriminant(B0);
    norm_gates := [IsSquare(dB),IsSquare(dA),IsSquare(dA*dB)];
    split_gates := [IsSquare(dB),IsSquare(dA),
                    IsSquare(dA) and IsSquare(dB)];
    labels := ["U=[B0,L]","V=[L,A0]","W=[A0,B0]"];
    halved := [];
    halves := [* *];
    for i in [1..3] do
        isdiv,half := IsDivisibleBy(dual_classes[i],2);
        Append(~halved,isdiv); Append(~halves,isdiv select half else Jd!0);
        assert not isdiv or split_gates[i];
        E1,E0 := HalvingEquations(MakeMonic(dual_factors[i]),g);
        print "HALVING",labels[i],"norm_gate",norm_gates[i],
            "split_gate",split_gates[i],"exact",isdiv,
            "equation_degrees",[TotalDegree(E1),TotalDegree(E0)],
            "equation_terms",[#Terms(E1),#Terms(E0)];
        if print_halving_equations then
            print " E1",E1; print " E0",E0;
        end if;
        if isdiv then
            assert 2*half eq dual_classes[i] and Order(half) eq 4;
            print " HALF",half;
        end if;
        if solve_affine_halves then
            cand := AffineHalves(MakeMonic(dual_factors[i]),g);
            print " AFFINE_HALF_COUNT",#cand;
            for h in cand do
                H := Jd![h[3],-scaleD*h[4] mod h[3]];
                assert 2*H eq dual_classes[i] and Order(H) eq 4;
            end for;
        end if;
    end for;

    Gd,phid := TorsionSubgroup(Jd);
    invD := Invariants(Gd);
    exponentD := GroupExponent(invD);
    ok60 := false; P60 := Jd!0;
    if exponentD mod 60 eq 0 then
        ok60,P60,a60 := PointOfExactOrder(Gd,phid,60);
        assert ok60 and Order(P60) eq 60;
    end if;
    simple,method,pcert,Phi := FullSimplicityCertificate(gI);

    print "RATIONAL_CONTACT30_C3ROOT_RICHELOT";
    print "chart",chart_label,"u",u,"s",s,"q",q,"rho",rho;
    print "coefficients", "A",aa,"B",bb,"C",Cc,"c",c,"e",ee,"d",dd;
    print "source_f",f,"integral_scale",scaleS,"integral_f",fI;
    print "source_contact_orders",ords,"source_torsion",invS,
        "source_torsion_order",GroupOrder(invS);
    print "source_kernel",A0,B0,L,"kernel_relation",TA+TB+TL eq Js!0;
    print "odd_transport", "source_P15_order",Order(P15),
        "kernel_is_2_primary",true,"codomain_has_order15",true;
    print "Delta",Delta,"dual_factors",U,V,W;
    print "dual_g",g,"integral_scale",scaleD,"integral_g",gI;
    print "discriminants",dA,dB,"norm_gates_UVW",norm_gates,
        "split_gates_UVW",split_gates;
    print "halved_UVW",halved,"dual_torsion",invD,
        "dual_torsion_order",GroupOrder(invD),"dual_exponent",exponentD;
    print "has_exact_order60_point",ok60;
    if ok60 then print "P60",P60; end if;
    print "geometrically_simple_certificate",simple,"method",method,
        "p",pcert,"Phi",Phi;
end procedure;

if mode eq "selftest" then
    print "CONTACT30_C3ROOT_RICHELOT_SELFTEST";
    SymbolicResultantProof();
    // V-only, U-only, and W-only positive controls.
    FiniteControl(11,9,-1,2,[2,60],[false,true,false]);
    FiniteControl(17,6,-1,8,[2,120],[true,false,false]);
    FiniteControl(47,8,-1,18,[2,2,600],[false,false,true]);
    RationalMumfordPositiveControl();
    print "SELFTEST_OK";
    quit;
end if;

if not (assigned rho_num and assigned rho_den) then
    error "rational mode requires rho_num and rho_den";
end if;
rho := Q!AsInteger(rho_num)/AsInteger(rho_den);
if assigned R_num or assigned R_den then
    if not (assigned R_num and assigned R_den and assigned branch) then
        error "R chart requires R_num, R_den, and branch";
    end if;
    rpar := Q!AsInteger(R_num)/AsInteger(R_den);
    b := AsInteger(branch);
    if b notin {-1,1} then error "branch must be -1 or 1"; end if;
    ok,data := ContactDataFromR(rpar,b);
    if not ok then error "boundary R parameter"; end if;
    VerifyRationalPoint(data,rho,"R");
else
    if not (assigned u_num and assigned u_den and assigned s_num and assigned s_den) then
        error "compact chart requires u_num,u_den,s_num,s_den";
    end if;
    u := Q!AsInteger(u_num)/AsInteger(u_den);
    s := Q!AsInteger(s_num)/AsInteger(s_den);
    ok,data := ContactDataFromUS(u,s);
    if not ok then error "boundary compact parameter"; end if;
    VerifyRationalPoint(data,rho,"us");
end if;

quit;
