#!/usr/bin/env sage -python
"""Extra independent 2-torsion conditions on the reconstructed Elkies N=32 family."""

from __future__ import annotations

from pathlib import Path
from sage.all import PolynomialRing, QQ, gcd

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "elkies32_extra2_conditions.txt"


def main():
    R = PolynomialRing(QQ, ("z", "r", "s"))
    z, r, s = R.gens()
    K = R.fraction_field()

    pnum = ((z - 2)*(r + 1)**2*(z**2*r + z**2 - 4*r)
            *(z**4*r**2 + 2*z**4*r - 10*z**3*r**2 + z**4
              - 16*z**3*r + 28*z**2*r**2 - 6*z**3 + 44*z**2*r
              - 16*z*r**2 + 16*z**2 - 56*z*r + 16*r**2
              - 24*z + 32*r + 16))
    pden = (r*z*(z**8*r**4 + 4*z**8*r**3 - 24*z**7*r**4
            + 48*z**6*r**5 + 6*z**8*r**2 - 80*z**7*r**3
            + 284*z**6*r**4 - 256*z**5*r**5 + 4*z**8*r
            - 100*z**7*r**2 + 632*z**6*r**3 - 1200*z**5*r**4
            + 320*z**4*r**5 + z**8 - 56*z**7*r + 672*z**6*r**2
            - 2432*z**5*r**3 + 2224*z**4*r**4 - 12*z**7
            + 344*z**6*r - 2496*z**5*r**2 + 5312*z**4*r**3
            - 2304*z**3*r**4 + 68*z**6 - 1248*z**5*r
            + 5808*z**4*r**2 - 7232*z**3*r**3 + 1664*z**2*r**4
            - 240*z**5 + 2976*z**4*r - 8832*z**3*r**2
            + 6272*z**2*r**3 - 768*z*r**4 + 576*z**4
            - 4800*z**3*r + 8640*z**2*r**2 - 3328*z*r**3
            + 256*r**4 - 960*z**3 + 5120*z**2*r - 5120*z*r**2
            + 1024*r**3 + 1088*z**2 - 3328*z*r + 1536*r**2
            - 768*z + 1024*r + 256))
    p = 4*K(pnum) / K(pden)
    a = K(z) * p
    c = (-p*z**4 + 4*p*z**3 - 8*p*z**2 + 8*z**2 + 8*p*z - 16)/(4*z**2)
    b = p*(z - 1) + c - 1
    h = a*s**3 + b*s**2 + c*s + 1
    fs = h**2 - a**2*s**5*(s + 1)
    H = R(fs.numerator())
    C32 = (3*z**4*r**4 + 9*z**4*r**3 - 16*z**3*r**4 + 10*z**4*r**2
           - 56*z**3*r**3 + 32*z**2*r**4 + 5*z**4*r - 72*z**3*r**2
           + 144*z**2*r**3 - 64*z*r**4 + z**4 - 40*z**3*r
           + 208*z**2*r**2 - 224*z*r**3 + 80*r**4 - 8*z**3
           + 120*z**2*r - 288*z*r**2 + 160*r**3 + 24*z**2
           - 160*z*r + 160*r**2 - 32*z + 80*r + 16)
    H_diag = R(H.subs({s: r}))
    qdiag, remdiag = H_diag.quo_rem(C32)

    lines = []
    lines.append("# Elkies N=32 reconstructed family: extra independent 2-torsion condition")
    lines.append("")
    lines.append("The built-in root r gives the 2-torsion class 16D.  To force an independent")
    lines.append("2-torsion class, impose f(s)=0 for a rational s != r.")
    lines.append("")
    lines.append("After substituting p=4*Pnum(z,r)/Pden(z,r) and the reconstructed formulas for a,b,c,")
    lines.append("let Hextra(z,r,s) be the numerator of f(s).  The extra-root cover is")
    lines.append("  C32(z,r)=0, Hextra(z,r,s)=0, s != r,")
    lines.append("with the diagonal component s=r removed/saturated, away from boundary denominators")
    lines.append("z*r*Pden*disc(f)=0.")
    lines.append("")
    lines.append(f"Pnum degrees (z,r): ({pnum.degree(z)}, {pnum.degree(r)}), terms={len(pnum.dict())}")
    lines.append(f"Pden degrees (z,r): ({pden.degree(z)}, {pden.degree(r)}), terms={len(pden.dict())}")
    lines.append(f"Numerator Hextra=f(s) degrees (z,r,s): ({H.degree(z)}, {H.degree(r)}, {H.degree(s)}), terms={len(H.dict())}")
    lines.append(f"Diagonal check: Hextra(z,r,r) remainder on division by C32 is {remdiag}")
    lines.append(f"Diagonal quotient degrees (z,r): ({qdiag.degree(z)}, {qdiag.degree(r)}), terms={len(qdiag.dict())}")
    lines.append("")
    lines.append("Hextra is too large to print in notes; it is regenerated by this script.")
    lines.append("The search script tests the saturated condition by exact factorization of f(x) and requiring a root s != r.")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
