//////////////////////////////////////////////////////////////////////
//  Root-swap quotient of the projected M(12)+contact-5 component P55.
//
//  Swapping the two roots of T+1 acts on normalized coordinates by
//
//    b -> 1-b,
//    u -> (1-b)u/(b+(2b-1)u).
//
//  Put t=2b-1 and use the Cayley cross-ratio coordinate
//
//    v = t*u/(1+t*(1+u)).
//
//  Then root swap is the linear involution (t,v)->(-t,-v).  Its invariant
//  ring is generated by q=t^2, r=v^2, p=t*v with p^2=q*r.  The transformed
//  P55 equation is even or odd under simultaneous sign.  Splitting its
//  monomials yields an exact plane equation for the quotient.
//////////////////////////////////////////////////////////////////////

SetColumns(0);
if not assigned mode then mode := "summary"; end if;
if mode notin {"summary","genus"} then error "mode summary or genus"; end if;
if not assigned MemGB then MemGB := 8;
elif Type(MemGB) eq MonStgElt then MemGB := StringToInteger(MemGB); end if;
SetMemoryLimit(MemGB*10^9);

Q := Rationals(); Z := Integers();

function Primitive(poly)
    if poly eq 0 then return poly; end if;
    den := LCM([Denominator(c) : c in Coefficients(poly)]);
    vals := [Z!(den*c) : c in Coefficients(poly)];
    cont := GCD(vals); if cont eq 0 then cont := 1; end if;
    return Parent(poly)!((Q!den/Q!Abs(cont))*poly);
end function;

// Reconstruct P55 exactly.
R<b,w,u> := PolynomialRing(Q,3,"grevlex");
PX<x> := PolynomialRing(R);
L := b+(2*b-1)*x;
A := x+w*(1+b*x);
F := L*(L*A^2+4*b*(1+x)^2*(w*L-x^2));
A0 := R!Evaluate(F,u); A1 := R!Evaluate(Derivative(F),u);
A2 := R!Evaluate(Derivative(F,2),u)/2;
A3 := R!Evaluate(Derivative(F,3),u)/6;
A4 := R!Evaluate(Derivative(F,4),u)/24;
Q2 := 4*A0*A2-A1^2;
E3 := Primitive(8*A0^2*A3-A1*Q2);
E4 := Primitive(64*A0^3*A4-Q2^2);
E3 := ExactQuotient(E3,b); E4 := ExactQuotient(E4,b);
Res3 := Resultant(E3,E4,w);
B2<B,U> := PolynomialRing(Q,2,"grevlex");
toB2 := hom<R -> B2 | B,B2!0,U>;
Res := Primitive(B2!toB2(Res3));
for h in [B,B-1,2*B-1] do
    while IsDivisibleBy(Res,h) do Res := ExactQuotient(Res,h); end while;
end for;
P55 := [fe[1] : fe in Factorization(Res) | TotalDegree(fe[1]) eq 55][1];
P55 := Primitive(P55);
assert IsIrreducible(P55);
print "P55_ROOTSWAP_INPUT",<TotalDegree(P55),Degree(P55,B),Degree(P55,U),#Terms(P55)>;

// Exact root-swap semi-invariance in the original plane.
KB := FieldOfFractions(B2);
Lb := B+(2*B-1)*U;
sw := Evaluate(KB!P55,[KB!(1-B),KB!((1-B)*U/Lb)]);
swnum := Primitive(B2!Numerator(sw));
swapgcd := GCD(swnum,P55);
print "P55_ROOTSWAP_GCD",<TotalDegree(swapgcd),Degree(swapgcd,B),Degree(swapgcd,U),#Terms(swapgcd)>,
      "swapped_numerator",<TotalDegree(swnum),Degree(swnum,B),Degree(swnum,U),#Terms(swnum)>;
if not IsDivisibleBy(swnum,P55) then
    print "P55_ROOTSWAP_NUMERATOR_FACTORS",
          [<TotalDegree(fe[1]),fe[2],Degree(fe[1],B),Degree(fe[1],U),#Terms(fe[1])>
           : fe in Factorization(swnum)];
    error "root-swap formula does not stabilize P55";
end if;
swapquot := Primitive(ExactQuotient(swnum,P55));
print "P55_ROOTSWAP_QUOTIENT_FACTOR degree",TotalDegree(swapquot),
      "terms",#Terms(swapquot),"factorization",Factorization(swapquot);

// Birational Cayley chart making the involution simultaneous sign.
TV<t,v> := PolynomialRing(Q,2,"grevlex");
KTV := FieldOfFractions(TV);
bm := KTV!((1+t)/2);
um := KTV!((1+t)*v/(t*(1-v)));
GtRaw := Evaluate(KTV!P55,[bm,um]);
GtNum := Primitive(TV!Numerator(GtRaw));
gtfac := Factorization(GtNum);
print "P55_TV_NUMERATOR",<TotalDegree(GtNum),#Terms(GtNum)>,
      "factors",[<TotalDegree(fe[1]),fe[2],#Terms(fe[1])> : fe in gtfac];

// The birational image is the unique non-linear factor of largest degree.
maxdeg := Max([TotalDegree(fe[1]) : fe in gtfac]);
cores := [fe[1] : fe in gtfac | TotalDegree(fe[1]) eq maxdeg];
assert #cores eq 1;
Core := Primitive(cores[1]);
CoreNeg := Primitive(Evaluate(Core,[-t,-v]));
parity := 0;
if CoreNeg eq Core then parity := 1;
elif CoreNeg eq -Core then parity := -1;
else error "transformed core is not a simultaneous-sign semi-invariant";
end if;
print "P55_TV_CORE",<TotalDegree(Core),Degree(Core,t),Degree(Core,v),#Terms(Core)>,
      "sign_parity",parity;

// Exact invariant field: q=t^2 and p=t*v generate Q(t,v)^{+/-1} because
// v^2=p^2/q.  If Core is odd, multiply its equation by t (safe on the
// open t!=0 chart) before converting monomials.  A monomial t^i v^j then
// becomes q^((i+shift-j)/2) p^j; one global q-power clears negatives.
QP<qe,pe> := PolynomialRing(Q,2,"grevlex");
shift := 0; if parity eq -1 then shift := 1; end if;
qexps := [];
for mon in Monomials(Core) do
    ex := Exponents(mon);
    assert (ex[1]+shift-ex[2]) mod 2 eq 0;
    Append(~qexps,(ex[1]+shift-ex[2]) div 2);
end for;
qshift := -Min(qexps);
if qshift lt 0 then qshift := 0; end if;
ExactQuot := QP!0;
mons0 := Monomials(Core); coeffs0 := Coefficients(Core);
for idx in [1..#mons0] do
    ex := Exponents(mons0[idx]);
    ExactQuot +:= coeffs0[idx]*qe^(qshift+(ex[1]+shift-ex[2]) div 2)*pe^ex[2];
end for;
ExactQuot := Primitive(ExactQuot);
while IsDivisibleBy(ExactQuot,qe) do ExactQuot := ExactQuotient(ExactQuot,qe); end while;
exactfac := Factorization(ExactQuot);
print "P55_EXACT_ROOTSWAP_QUOTIENT",
      <TotalDegree(ExactQuot),Degree(ExactQuot,qe),Degree(ExactQuot,pe),#Terms(ExactQuot)>,
      "q_clear_shift",qshift,
      "factors",[<TotalDegree(fe[1]),fe[2],Degree(fe[1],qe),Degree(fe[1],pe),#Terms(fe[1])> : fe in exactfac];

// Write the invariant quotient equation.
QR<q,r> := PolynomialRing(Q,2,"grevlex");
AA := QR!0; BB := QR!0;
mons := Monomials(Core); coeffs := Coefficients(Core);
for idx in [1..#mons] do
    ex := Exponents(mons[idx]); i := ex[1]; j := ex[2]; cc := coeffs[idx];
    if parity eq 1 then
        assert (i+j) mod 2 eq 0;
        if i mod 2 eq 0 then
            assert j mod 2 eq 0;
            AA +:= cc*q^(i div 2)*r^(j div 2);
        else
            assert j mod 2 eq 1;
            BB +:= cc*q^((i-1) div 2)*r^((j-1) div 2);
        end if;
    else
        assert (i+j) mod 2 eq 1;
        if i mod 2 eq 1 then
            assert j mod 2 eq 0;
            AA +:= cc*q^((i-1) div 2)*r^(j div 2);
        else
            assert j mod 2 eq 1;
            BB +:= cc*q^(i div 2)*r^((j-1) div 2);
        end if;
    end if;
end for;
AA := Primitive(AA); BB := Primitive(BB);
if parity eq 1 then
    Quot := Primitive(AA^2-q*r*BB^2);
else
    Quot := Primitive(q*AA^2-r*BB^2);
end if;
print "P55_INVARIANT_SPLIT","A",<TotalDegree(AA),Degree(AA,q),Degree(AA,r),#Terms(AA)>,
      "B",<TotalDegree(BB),Degree(BB,q),Degree(BB,r),#Terms(BB)>;
qfac := Factorization(Quot);
print "P55_QUOTIENT_RAW",<TotalDegree(Quot),Degree(Quot,q),Degree(Quot,r),#Terms(Quot)>,
      "factors",[<TotalDegree(fe[1]),fe[2],Degree(fe[1],q),Degree(fe[1],r),#Terms(fe[1])> : fe in qfac];

// Strip only q=0/r=0 Cayley boundary factors.  Any other factor is retained.
Qopen := Quot;
for h in [q,r] do while IsDivisibleBy(Qopen,h) do Qopen := ExactQuotient(Qopen,h); end while; end for;
ofac := Factorization(Qopen);
print "P55_QUOTIENT_OPEN",<TotalDegree(Qopen),Degree(Qopen,q),Degree(Qopen,r),#Terms(Qopen)>,
      "factors",[<TotalDegree(fe[1]),fe[2],Degree(fe[1],q),Degree(fe[1],r),#Terms(fe[1])> : fe in ofac];

if mode eq "summary" then print "P55_ROOTSWAP_DONE"; quit; end if;

for idx in [1..#exactfac] do
    hq := exactfac[idx][1];
    P2<Qh,Rh,Zh> := ProjectiveSpace(Q,2);
    hh := Homogenization(Evaluate(hq,[Qh,Rh]),Zh);
    Cq := Curve(P2,hh);
    print "P55_QUOTIENT_COMPONENT",idx,"degree",Degree(Cq),
          "arithmetic_genus",(Degree(Cq)-1)*(Degree(Cq)-2) div 2;
    time gq := Genus(Cq);
    print " normalized_genus",gq;
end for;
print "P55_ROOTSWAP_GENUS_DONE";
quit;
