
//////////////////////////////////////////////////////////////////////
//  2-primary divisibility diagnostic for the M_1(8,4) tangent family.
//
//  For a specialization C: y^2 = x*A*B, the generic rational 2-torsion
//  is generated by the classes T_x=[x,0], T_A=[A,0], T_B=[B,0]
//  with T_x+T_A+T_B=0.  This script checks which of these classes are
//  divisible by 2 repeatedly, and prints exact torsion.
//////////////////////////////////////////////////////////////////////

SetColumns(0);

Q := Rationals();
P<x> := PolynomialRing(Q);

if not assigned Rval then
    Rval := Q!-8;
elif Type(Rval) eq MonStgElt then
    Rval := StringToRational(Rval);
else
    Rval := Q!Rval;
end if;

if not assigned wval then
    wval := Q!6;
elif Type(wval) eq MonStgElt then
    wval := StringToRational(wval);
else
    wval := Q!wval;
end if;

function IntegralModelPolynomial(f)
    L := 1;
    for i in [0..Degree(f)] do
        L := LCM(L, Denominator(Coefficient(f, i)));
    end for;
    return P!(L^2*f), L;
end function;

function FamilyPolynomial(R, w)
    m := R;
    n := Q!1;
    t := (2*m^2 + (1-w^2)*m*n - 2*w^2*n^2)/(4*(w^2-1));
    A := n^4*x^2
         + (m^3*n + 4*m^2*t + m*n^3 - 8*m*n*t + 4*n^2*t)*x
         + m^4;
    B := (m*n + 2*n^2 + 4*t)*x^2
         + (m^2 + 4*m*n + n^2 + 8*t)*x
         + (2*m^2 + m*n + 4*t);
    return x*A*B, t, A, B;
end function;

function Monic(g)
    return g/LeadingCoefficient(g);
end function;

procedure DivChain(label, J, D)
    print label, "order", Order(D);
    current := D;
    for k in [1..5] do
        ok, H := IsDivisibleBy(current, 2);
        print "  divisible_step", k, ok;
        if not ok then
            break;
        end if;
        print "  half_order", Order(H), "half", H;
        current := H;
    end for;
end procedure;

f, t, A, B := FamilyPolynomial(Rval, wval);
fI, L := IntegralModelPolynomial(f);
C := HyperellipticCurve(fI);
J := Jacobian(C);
G, phi := TorsionSubgroup(J);
print "R", Rval, "w", wval, "t", t;
print "torsion", Invariants(G);
print "A", A;
print "B", B;
print "fI", fI;

Tx := J![x, Q!0];
TA := J![Monic(A), Q!0];
TB := J![Monic(B), Q!0];
print "relation Tx+TA+TB zero", Tx + TA + TB eq J!0;
Y_R := -2*Rval*(Rval-1)^2*(Rval^2 - (Q!1/2)*Rval*wval^2 + (Q!1/2)*Rval - wval^2)/(wval^2-1);
print "P_R", <-Rval, Y_R>, "on_curve", Y_R^2 eq Evaluate(f, -Rval);
PR := J![x + Rval, Q!(L*Y_R)];
print "4*P_R eq TA", 4*PR eq TA, "minus", 4*PR eq -TA;
DivChain("P_R", J, PR);
DivChain("Tx", J, Tx);
DivChain("TA", J, TA);
DivChain("TB", J, TB);

quit;
