//////////////////////////////////////////////////////////////////////
//  Residue-driven integer tuple enumerator for M(2,2,2,4)+3.
//
//  Input:
//    data/m2224_plus3_live13_residues.txt
//  generated by m2224_plus3_live13_residues.py.  These are ordered
//  mod-13 base residues with a cover-open 13-adic first-order branch.
//
//  For each integer triple 0 < a < b < c <= height, this script only
//  generates d values whose mod-13 residue makes (a,b,c,d) land in one
//  of the live boundary classes.  It then applies good-prime point-count
//  residue filters and strict cubic-contact residue filters before writing
//  tuples.
//
//  Typical run:
//      magma -b height:=200 point_prime_bound:=73 contact_prime_bound:=37 \
//          output_file:="data/m2224_plus3_residue_H200_p73_c37.txt" \
//          code/m2224_plus3_residue_enum.m
//////////////////////////////////////////////////////////////////////

SetColumns(0);

if not assigned height then
    height := 100;
elif Type(height) eq MonStgElt then
    height := StringToInteger(height);
end if;

if not assigned point_prime_bound then
    point_prime_bound := 73;
elif Type(point_prime_bound) eq MonStgElt then
    point_prime_bound := StringToInteger(point_prime_bound);
end if;

if not assigned contact_prime_bound then
    contact_prime_bound := 37;
elif Type(contact_prime_bound) eq MonStgElt then
    contact_prime_bound := StringToInteger(contact_prime_bound);
end if;

if not assigned live13_file then
    live13_file := "data/m2224_plus3_live13_residues.txt";
end if;

if not assigned output_file then
    output_file := "data/m2224_plus3_residue_candidates.txt";
end if;

if not assigned max_rows then
    max_rows := 0;
elif Type(max_rows) eq MonStgElt then
    max_rows := StringToInteger(max_rows);
end if;

if not assigned progress_interval then
    progress_interval := 100000;
elif Type(progress_interval) eq MonStgElt then
    progress_interval := StringToInteger(progress_interval);
end if;

Q := Rationals();
Z := Integers();
P<x> := PolynomialRing(Q);
point_primes := [p : p in PrimesUpTo(point_prime_bound) | p notin {2,3,5,7,13}];
contact_primes := [p : p in PrimesUpTo(contact_prime_bound) | p notin {2,3,5,7,13}];

function ParseCSV4(line)
    pipe_parts := Split(line, "|");
    lhs := pipe_parts[1];
    parts := Split(lhs, ",");
    return [StringToInteger(parts[i]) : i in [1..4]];
end function;

function TripleKey(a,b,c)
    return <a,b,c>;
end function;

function ReadLive13DMap(filename)
    S := Read(filename);
    rows := Split(S, "\n");
    dmap := AssociativeArray();
    residue_count := 0;

    for row in rows do
        if #row eq 0 or row[1] eq "#" then
            continue;
        end if;
        vals := ParseCSV4(row);
        key := TripleKey(vals[1], vals[2], vals[3]);
        if IsDefined(dmap, key) then
            ds := dmap[key];
            Include(~ds, vals[4]);
            dmap[key] := ds;
        else
            dmap[key] := {Z | vals[4]};
        end if;
        residue_count +:= 1;
    end for;

    return dmap, residue_count;
end function;

function CurveKeyFromSquares(sq)
    A := sq[1]; B := sq[2]; C := sq[3]; D := sq[4];
    e1 := A+B+C+D;
    e2 := A*B + A*C + A*D + B*C + B*D + C*D;
    e3 := A*B*C + A*B*D + A*C*D + B*C*D;
    e4 := A*B*C*D;
    return <Z!e1, Z!e2, Z!e3, Z!e4>;
end function;

function CurveKeyModp(tup, p)
    F := GF(p);
    squares := [(F!a)^2 : a in tup];
    if &*squares eq 0 or #(Set(squares)) lt #squares then
        return false, <0,0,0,0>;
    end if;
    return true, CurveKeyFromSquares(squares);
end function;

function ContactCoefficientKeys(p)
    F := GF(p);
    PF<X> := PolynomialRing(F);
    keys := {};
    raw_count := 0;

    for L in F do
        if L eq 0 then
            continue;
        end if;
        M := L^2;
        for U in F do
            for v in F do
                if v eq 0 or U^2 - 4*v^2 eq 0 then
                    continue;
                end if;
                q := X^2 + U*X + v^2;
                for e1 in F do
                    A := 2*M*e1 + 6*(U^2+v^2) - (M+3*U)^2;
                    e2 := ((M+3*U)*A + 8*v^3 - 4*U^3 - 24*U*v^2)/(4*M);
                    e3 := (A^2 + 16*(M+3*U)*v^3
                           - 48*(U^2*v^2+v^4))/(16*M);
                    e4 := (A*v^3 - 6*U*v^4)/(2*M);
                    if e4 eq 0 then
                        continue;
                    end if;
                    f := X^5 + e1*X^4 + e2*X^3 + e3*X^2 + e4*X;
                    if Degree(GCD(q, f)) gt 0 then
                        continue;
                    end if;
                    Include(~keys, <Z!e1, Z!e2, Z!e3, Z!e4>);
                    raw_count +:= 1;
                end for;
            end for;
        end for;
    end for;

    return keys, raw_count;
end function;

function PrecomputeContactData(primes)
    data := AssociativeArray();
    for p in primes do
        keys, raw_count := ContactCoefficientKeys(p);
        data[p] := keys;
        print "prime", p, "contact_keys", #keys, "raw_contact_param", raw_count;
    end for;
    return data;
end function;

function PassesContactFilters(tup, contact_data)
    for p in Keys(contact_data) do
        good, key := CurveKeyModp(tup, p);
        if good and not (key in contact_data[p]) then
            return false, p;
        end if;
    end for;
    return true, 0;
end function;

function PointCountAllowedKeys(p)
    F := GF(p);
    PF<X> := PolynomialRing(F);
    squares := Setseq({a^2 : a in F | a ne 0});
    allowed := {};
    total := 0;

    for i in [1..#squares-3] do
        for j in [i+1..#squares-2] do
            for k in [j+1..#squares-1] do
                for l in [k+1..#squares] do
                    branch := [squares[i], squares[j], squares[k], squares[l]];
                    key := CurveKeyFromSquares(branch);
                    f := X;
                    for s in branch do
                        f *:= X + s;
                    end for;
                    C := HyperellipticCurve(f);
                    n := Z!#Jacobian(C);
                    total +:= 1;
                    if n mod 3 eq 0 then
                        Include(~allowed, key);
                    end if;
                end for;
            end for;
        end for;
    end for;

    return allowed, total;
end function;

function PrecomputePointCountData(primes)
    data := AssociativeArray();
    for p in primes do
        allowed, total := PointCountAllowedKeys(p);
        data[p] := allowed;
        print "prime", p, "point_keys", total, "allowed_3div", #allowed;
    end for;
    return data;
end function;

function PassesPointCountFilters(tup, point_count_data)
    for p in Keys(point_count_data) do
        good, key := CurveKeyModp(tup, p);
        if good and not (key in point_count_data[p]) then
            return false, p;
        end if;
    end for;
    return true, 0;
end function;

function FirstInIntervalWithResidue(lo, hi, residue, modulus)
    if lo gt hi then
        return hi + 1;
    end if;
    shift := (residue - lo) mod modulus;
    return lo + shift;
end function;

function TupleKey(tup)
    return Sprint(tup);
end function;

print "M(2,2,2,4)+3 residue-driven tuple enumerator";
print "height", height,
      "point_prime_bound", point_prime_bound,
      "point_primes", point_primes,
      "contact_prime_bound", contact_prime_bound,
      "contact_primes", contact_primes;
print "live13_file", live13_file;
print "output_file", output_file;

dmap, live_count := ReadLive13DMap(live13_file);
print "live13_residues", live_count, "live13_triples", #Keys(dmap);
point_count_data := PrecomputePointCountData(point_primes);
contact_data := PrecomputeContactData(contact_primes);

out := Open(output_file, "w");
checked_triples := 0;
live_triples := 0;
live_d_candidates := 0;
point_survivors := 0;
contact_survivors := 0;
unique_rows := 0;
seen := {""};
Exclude(~seen, "");
point_kill_counts := AssociativeArray();
contact_kill_counts := AssociativeArray();

for a in [1..height-2] do
    for b in [a+1..height-1] do
        for c in [b+1..height] do
            checked_triples +:= 1;
            key13 := TripleKey(a mod 13, b mod 13, c mod 13);
            if not IsDefined(dmap, key13) then
                continue;
            end if;
            live_triples +:= 1;
            ds := dmap[key13];
            for rd in ds do
                d0 := FirstInIntervalWithResidue(c+1, height, rd, 13);
                d := d0;
                while d le height do
                    tup := [a,b,c,d];
                    if GCD(tup) eq 1 then
                        live_d_candidates +:= 1;
                        pass, killp := PassesPointCountFilters(tup, point_count_data);
                        if pass then
                            point_survivors +:= 1;
                            cpass, ckillp := PassesContactFilters(tup, contact_data);
                            if cpass then
                                contact_survivors +:= 1;
                                tkey := TupleKey(tup);
                                if tkey notin seen then
                                    Include(~seen, tkey);
                                    fprintf out, "%o\n", tup;
                                    unique_rows +:= 1;
                                    if max_rows gt 0 and unique_rows ge max_rows then
                                        print "MAX_ROWS_REACHED", max_rows;
                                        print "SUMMARY checked_triples", checked_triples,
                                              "live_triples", live_triples,
                                              "live_d_candidates", live_d_candidates,
                                              "point_survivors", point_survivors,
                                              "contact_survivors", contact_survivors,
                                              "unique_rows", unique_rows;
                                        quit;
                                    end if;
                                end if;
                            else
                                if IsDefined(contact_kill_counts, ckillp) then
                                    contact_kill_counts[ckillp] +:= 1;
                                else
                                    contact_kill_counts[ckillp] := 1;
                                end if;
                            end if;
                        else
                            if IsDefined(point_kill_counts, killp) then
                                point_kill_counts[killp] +:= 1;
                            else
                                point_kill_counts[killp] := 1;
                            end if;
                        end if;
                    end if;
                    d +:= 13;
                end while;
            end for;

            if progress_interval gt 0 and checked_triples mod progress_interval eq 0 then
                print "progress", checked_triples,
                      "live_triples", live_triples,
                      "live_d_candidates", live_d_candidates,
                      "point_survivors", point_survivors,
                      "contact_survivors", contact_survivors,
                      "unique_rows", unique_rows;
            end if;
        end for;
    end for;
end for;

print "SUMMARY checked_triples", checked_triples,
      "live_triples", live_triples,
      "live_d_candidates", live_d_candidates,
      "point_survivors", point_survivors,
      "contact_survivors", contact_survivors,
      "unique_rows", unique_rows;
print "point_kill_counts";
for p in Sort([k : k in Keys(point_kill_counts)]) do
    print p, point_kill_counts[p];
end for;
print "contact_kill_counts";
for p in Sort([k : k in Keys(contact_kill_counts)]) do
    print p, contact_kill_counts[p];
end for;

quit;
