/*
 * Fast rational-height sieve on the simple M(2,12) line a=(1-r)/4.
 *
 * The masks are generated by m612_m212_line_contact_sieve.py.  For a good
 * finite residue r mod p, the mask retains r exactly when the normalized odd
 * quintic has at least two distinct cubic-contact q-supports.  Bad residues
 * and the projective infinity residue are conservatively retained.
 *
 * We enumerate primitive r=n/d, |n|<=H, 1<=d<=H.  Four especially strong
 * masks (p=5,11,41,53) are combined by CRT before any candidate numerator is
 * visited.  The remaining masks are ordered by density.
 *
 * Build/run from torsion_jac:
 *
 *   cc -O3 -march=native code/m612_m212_line_height_sieve.c \
 *      -o /tmp/m612_m212_line_height_sieve
 *   /tmp/m612_m212_line_height_sieve 100000
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

typedef struct {
    int p;
    int n;
    const uint8_t *a;
} Mask;

static const uint8_t A5[]  = {0,1,4};
static const uint8_t A7[]  = {0,1,5,6};
static const uint8_t A11[] = {0,1,10};
static const uint8_t A13[] = {0,1,4,12};
static const uint8_t A17[] = {0,1,6,7,8,13,15,16};
static const uint8_t A19[] = {0,1,2,10,12,13,15,16,18};
static const uint8_t A23[] = {0,1,2,7,9,20,22};
static const uint8_t A29[] = {0,1,8,12,14,16,18,28};
static const uint8_t A31[] = {0,1,3,5,7,10,17,18,19,20,24,25,28,30};
static const uint8_t A37[] = {0,1,4,5,9,11,14,18,21,23,25,27,28,31,33,35,36};
static const uint8_t A41[] = {0,1,5,19,26,27,32,40};
static const uint8_t A43[] = {0,1,3,5,9,11,14,19,24,25,26,33,34,35,36,38,39,42};
static const uint8_t A47[] = {0,1,5,6,9,14,18,29,31,34,38,42,46};
static const uint8_t A53[] = {0,1,3,4,20,23,33,41,52};
static const uint8_t A59[] = {0,1,9,27,34,40,44,55,57,58};
static const uint8_t A61[] = {0,1,2,4,8,12,13,15,19,21,22,26,30,36,38,48,51,55,59,60};
static const uint8_t A67[] = {0,1,7,9,10,13,20,23,24,26,27,28,31,32,33,34,39,42,45,55,57,59,66};
static const uint8_t A71[] = {0,1,2,6,11,14,18,20,24,26,36,40,41,44,47,48,50,61,70};
static const uint8_t A73[] = {0,1,2,5,9,11,12,14,22,23,25,26,31,34,41,43,45,50,51,52,58,60,62,64,69,71,72};
static const uint8_t A79[] = {0,1,9,11,22,27,30,34,35,37,39,42,45,46,48,49,50,54,56,57,64,66,72,75,78};
static const uint8_t A83[] = {0,1,7,11,13,24,27,49,54,56,58,59,61,65,70,72,74,78,82};
static const uint8_t A89[] = {0,1,8,10,11,27,45,55,64,66,70,78,83,88};

#define MASK(P,A) {(P), (int)(sizeof(A)/sizeof((A)[0])), (A)}

/* CRT base product 5*11*41*53 = 119515. */
static const Mask base_masks[] = {
    MASK(5,A5), MASK(11,A11), MASK(41,A41), MASK(53,A53)
};

/* Strongest remaining masks first. */
static const Mask test_masks[] = {
    MASK(89,A89), MASK(59,A59), MASK(83,A83), MASK(71,A71),
    MASK(47,A47), MASK(29,A29),
    MASK(23,A23), MASK(61,A61), MASK(67,A67), MASK(79,A79),
    MASK(13,A13), MASK(73,A73), MASK(7,A7), MASK(43,A43),
    MASK(37,A37), MASK(31,A31), MASK(17,A17), MASK(19,A19)
};

static int64_t H;
static uint64_t crt_leaves = 0, bounded_pairs = 0, primitive_pairs = 0;
static uint64_t survivors = 0;
static uint64_t killed[sizeof(test_masks)/sizeof(test_masks[0])] = {0};

static int igcd(int64_t a, int64_t b) {
    if (a < 0) a = -a;
    while (b) {
        int64_t t = a % b;
        a = b;
        b = t;
    }
    return (int)a;
}

static int invmod(int a, int p) {
    int t = 0, nt = 1, r = p, nr = a % p;
    if (nr < 0) nr += p;
    while (nr) {
        int q = r / nr;
        int z = t - q * nt; t = nt; nt = z;
        z = r - q * nr; r = nr; nr = z;
    }
    if (t < 0) t += p;
    return t;
}

static int allowed_affine(const Mask *m, int r) {
    for (int i = 0; i < m->n; ++i)
        if ((int)m->a[i] == r) return 1;
    return 0;
}

static int passes_remaining(int64_t n, int64_t d) {
    const int nt = (int)(sizeof(test_masks)/sizeof(test_masks[0]));
    for (int i = 0; i < nt; ++i) {
        const Mask *m = &test_masks[i];
        int p = m->p;
        int dm = (int)(d % p);
        if (dm == 0) continue; /* projective infinity: conservatively allowed */
        int nm = (int)(n % p); if (nm < 0) nm += p;
        int r = nm * invmod(dm, p) % p;
        if (!allowed_affine(m, r)) {
            ++killed[i];
            return 0;
        }
    }
    return 1;
}

static int64_t floor_div(int64_t a, int64_t b) {
    int64_t q = a / b, r = a % b;
    if (r && ((r > 0) != (b > 0))) --q;
    return q;
}

static int64_t ceil_div(int64_t a, int64_t b) {
    return -floor_div(-a, b);
}

static void visit_residue(int64_t residue, int64_t mod, int64_t d) {
    ++crt_leaves;
    int64_t k0 = ceil_div(-H - residue, mod);
    int64_t k1 = floor_div(H - residue, mod);
    for (int64_t k = k0; k <= k1; ++k) {
        int64_t n = residue + k * mod;
        ++bounded_pairs;
        if (igcd(n, d) != 1) continue;
        ++primitive_pairs;
        if (!passes_remaining(n, d)) continue;
        ++survivors;
        printf("SURVIVOR n=%lld d=%lld r=%lld/%lld\n",
               (long long)n, (long long)d,
               (long long)n, (long long)d);
    }
}

static void crt_recurse(int idx, int64_t residue, int64_t mod, int64_t d) {
    const int nb = (int)(sizeof(base_masks)/sizeof(base_masks[0]));
    if (idx == nb) {
        visit_residue(residue, mod, d);
        return;
    }
    const Mask *m = &base_masks[idx];
    int p = m->p;
    int dm = (int)(d % p);
    int modp = (int)(mod % p);
    int imod = invmod(modp, p);
    int r0 = (int)(residue % p);

    if (dm == 0) {
        /* Infinity branch.  Primitivity forces n != 0 mod p. */
        for (int target = 1; target < p; ++target) {
            int t = (target - r0) % p; if (t < 0) t += p;
            t = t * imod % p;
            crt_recurse(idx + 1, residue + mod * t, mod * p, d);
        }
    } else {
        for (int j = 0; j < m->n; ++j) {
            int target = dm * (int)m->a[j] % p;
            int t = (target - r0) % p; if (t < 0) t += p;
            t = t * imod % p;
            crt_recurse(idx + 1, residue + mod * t, mod * p, d);
        }
    }
}

int main(int argc, char **argv) {
    H = (argc > 1) ? atoll(argv[1]) : 100000;
    if (H < 1) return 2;
    fprintf(stderr, "M(2,12) line cubic-contact CRT sieve, H=%lld\n",
            (long long)H);
    for (int64_t d = 1; d <= H; ++d) {
        crt_recurse(0, 0, 1, d);
        if (d % 10000 == 0)
            fprintf(stderr, "d=%lld leaves=%llu primitive=%llu survivors=%llu\n",
                    (long long)d, (unsigned long long)crt_leaves,
                    (unsigned long long)primitive_pairs,
                    (unsigned long long)survivors);
    }
    fprintf(stderr,
            "DONE H=%lld leaves=%llu bounded=%llu primitive=%llu survivors=%llu\n",
            (long long)H, (unsigned long long)crt_leaves,
            (unsigned long long)bounded_pairs,
            (unsigned long long)primitive_pairs,
            (unsigned long long)survivors);
    for (int i = 0; i < (int)(sizeof(test_masks)/sizeof(test_masks[0])); ++i)
        fprintf(stderr, "kill p=%d count=%llu\n", test_masks[i].p,
                (unsigned long long)killed[i]);
    return 0;
}
