// Denominator-aware CRT sieve for the three explicit P^1 curves on the
// full A(2,2,2,8) cover.
//
// The input masks are generated by
//     target_22224_a2228_curves_plus3_masks.m
// using the necessary condition 3 | #J(F_p) at every good prime.  Boundary
// residues are retained.  No cubic-contact formula is used here.
//
// Build/run from torsion_jac:
//   c++ -O3 -std=c++17 code/target_22224_a2228_curves_plus3_crt.cpp \
//       -o /tmp/target_22224_a2228_curves_plus3_crt
//   /tmp/target_22224_a2228_curves_plus3_crt 100000 \
//       results/target_22224_a2228_curves_plus3_crt_h100000.tsv

#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <numeric>
#include <sstream>
#include <string>
#include <vector>

using i64 = long long;
using i128 = __int128_t;

struct Mask {
    int p = 0;
    std::vector<unsigned char> finite;
    std::vector<int> finite_list;
    std::vector<int> inverse;
    bool infinity = false;
};

static i64 mod_norm(i64 a, i64 m) {
    a %= m;
    if (a < 0) a += m;
    return a;
}

static i64 inverse_mod(i64 a, i64 p) {
    i64 t = 0, nt = 1, r = p, nr = mod_norm(a, p);
    while (nr) {
        i64 q = r / nr;
        i64 tmp = t - q * nt; t = nt; nt = tmp;
        tmp = r - q * nr; r = nr; nr = tmp;
    }
    return mod_norm(t, p);
}

static i64 floor_div(i64 a, i64 b) {
    i64 q = a / b, r = a % b;
    if (r && ((r > 0) != (b > 0))) --q;
    return q;
}

static i64 ceil_div(i64 a, i64 b) {
    return -floor_div(-a, b);
}

static std::vector<std::string> split_tab(const std::string &s) {
    std::vector<std::string> out;
    std::stringstream ss(s);
    std::string z;
    while (std::getline(ss, z, '\t')) out.push_back(z);
    return out;
}

static bool load_mask_file(const std::string &path, int p,
                           std::array<std::vector<Mask>, 6> &all) {
    std::ifstream in(path);
    if (!in) return false;
    std::array<Mask, 6> rows;
    for (int f = 0; f < 6; ++f) {
        rows[f].p = p;
        rows[f].finite.assign(p, 0);
        rows[f].inverse.assign(p, 0);
        for (int x = 1; x < p; ++x) rows[f].inverse[x] = (int)inverse_mod(x, p);
    }
    std::string line;
    std::getline(in, line);
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        auto c = split_tab(line);
        if (c.size() < 5) continue;
        int family = std::stoi(c[0]);
        int n = std::stoi(c[1]);
        int d = std::stoi(c[2]);
        if (family < 1 || family > 6) continue;
        if (d == 0) rows[family - 1].infinity = true;
        else rows[family - 1].finite[mod_norm(n, p)] = 1;
    }
    for (int f = 0; f < 6; ++f) {
        // A family absent from this file must not create an empty mask.
        bool present = rows[f].infinity;
        for (unsigned char z : rows[f].finite) present = present || (z != 0);
        if (!present) continue;
        for (int r = 0; r < p; ++r)
            if (rows[f].finite[r]) rows[f].finite_list.push_back(r);
        all[f].push_back(std::move(rows[f]));
    }
    return true;
}

static bool smooth_exact(int family, i64 n0, i64 d0) {
    const i128 n = n0, d = d0;
    std::array<i128, 4> a{};
    if (family == 1) {
        i128 q = n*n + n*d + d*d;
        a = {-q*q,
             -4*n*(n+d)*(n+d)*d,
              4*n*(n+d)*d*d,
              4*n*n*(n+d)*d};
    } else if (family == 2) {
        i128 n2=n*n,n3=n2*n,n4=n2*n2,d2=d*d,d3=d2*d,d4=d2*d2;
        i128 N=n4-2*n3*d-n2*d2+2*n*d3+d4;
        i128 D=n4+2*n3*d-n2*d2-2*n*d3+d4;
        a = {-n*d*N,-d2*D,n*d*D,n2*D};
    } else {
        if (family == 3) {
            a = {-n*(n+d)*(n+d)*d,
                 (n*n-d*d)*d*d,
                 -n*n*(n*n-d*d),
                 n*(n-d)*(n-d)*d};
        } else if (family == 4) {
            i128 N=n*(n+d)*(n+d)*(n-d);
            i128 D=(n*n-2*n*d-d*d)*(n*n+d*d);
            a = {-N*d*d,-n*n*D,d*d*D,n*d*D};
        } else {
            i128 A = family == 5 ? 16 : 144;
            i128 B = family == 5 ? 9 : 25;
            i128 D=A*d-B*n, N=B*d-A*n;
            a = {d*D,n*D,d*N,n*N};
        }
    }
    for (int i = 0; i < 4; ++i) {
        if (a[i] == 0) return false;
        for (int j = 0; j < i; ++j)
            if (a[i] == a[j] || a[i] == -a[j]) return false;
    }
    return true;
}

struct Searcher {
    i64 H;
    int family;
    std::vector<Mask> masks;
    std::ofstream &out;
    unsigned long long lattice_nodes = 0;
    unsigned long long boxed = 0;
    unsigned long long primitive = 0;
    unsigned long long smooth = 0;
    unsigned long long survivors = 0;

    bool passes(const Mask &m, i64 n, i64 d) const {
        int dm = (int)mod_norm(d, m.p);
        int nm = (int)mod_norm(n, m.p);
        if (dm == 0) return nm != 0 && m.infinity;
        int slope = (int)((i64)nm * m.inverse[dm] % m.p);
        return m.finite[slope] != 0;
    }

    void test_integer(i64 n, i64 d) {
        ++boxed;
        if (n == 0 || std::gcd(std::llabs(n), d) != 1) return;
        ++primitive;
        for (const auto &m : masks) if (!passes(m, n, d)) return;
        if (!smooth_exact(family, n, d)) return;
        ++smooth;
        out << family << '\t' << n << '\t' << d << '\n';
        ++survivors;
    }

    void enumerate_class(i64 residue, i64 modulus, i64 d) {
        i64 kmin = ceil_div(-H - residue, modulus);
        i64 kmax = floor_div(H - residue, modulus);
        for (i64 k = kmin; k <= kmax; ++k)
            test_integer(residue + k * modulus, d);
    }

    void recurse(std::size_t idx, i64 residue, i64 modulus, i64 d) {
        ++lattice_nodes;
        if (idx == masks.size() || modulus > 2 * H) {
            enumerate_class(residue, modulus, d);
            return;
        }
        const Mask &m = masks[idx];
        const int p = m.p;
        const int dm = (int)mod_norm(d, p);
        std::vector<int> nmods;
        if (dm == 0) {
            if (!m.infinity) return;
            nmods.reserve(p - 1);
            for (int x = 1; x < p; ++x) nmods.push_back(x);
        } else {
            nmods.reserve(m.finite_list.size());
            for (int slope : m.finite_list)
                nmods.push_back((int)((i64)slope * dm % p));
        }
        const i64 inv = inverse_mod(modulus % p, p);
        const i64 newmod = modulus * p;
        for (int target : nmods) {
            i64 k = mod_norm((target - residue) * inv, p);
            i64 nr = residue + modulus * k;
            // Once the modulus is wider than the box, prune empty classes
            // before descending to the remaining masks.
            if (newmod > 2 * H) {
                i64 kmin = ceil_div(-H - nr, newmod);
                i64 kmax = floor_div(H - nr, newmod);
                if (kmin > kmax) continue;
            }
            recurse(idx + 1, nr, newmod, d);
        }
    }

    void run() {
        std::sort(masks.begin(), masks.end(), [](const Mask &a, const Mask &b) {
            long long ca = (long long)a.finite_list.size() + (a.infinity ? 1 : 0);
            long long cb = (long long)b.finite_list.size() + (b.infinity ? 1 : 0);
            return ca * (b.p + 1LL) < cb * (a.p + 1LL);
        });
        std::cerr << "family " << family << " mask order";
        for (const auto &m : masks)
            std::cerr << " p" << m.p << "="
                      << (m.finite_list.size() + (m.infinity ? 1 : 0));
        std::cerr << "\n";
        for (i64 d = 1; d <= H; ++d) {
            recurse(0, 0, 1, d);
            if (d % 10000 == 0)
                std::cerr << "family " << family << " d=" << d
                          << " boxed=" << boxed << " survivors=" << survivors << "\n";
        }
        std::cerr << "FAMILY_DONE " << family
                  << " lattice_nodes=" << lattice_nodes
                  << " boxed=" << boxed
                  << " primitive=" << primitive
                  << " smooth=" << smooth
                  << " survivors=" << survivors << "\n";
    }
};

int main(int argc, char **argv) {
    i64 H = argc > 1 ? std::atoll(argv[1]) : 100000;
    std::string output = argc > 2 ? argv[2]
        : "results/target_22224_a2228_curves_plus3_crt.tsv";
    std::string prefix = argc > 3 ? argv[3]
        : "results/target_22224_a2228_curves_plus3_masks_p";
    const std::vector<int> primes = {
        5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,
        83,89,97,101,103,107,109,113,127,131,137,139,149,151,157,163,
        167,173,179,181,191,193,197,199
    };
    std::array<std::vector<Mask>, 6> all;
    int loaded = 0;
    for (int p : primes) {
        std::string path = prefix + std::to_string(p) + ".tsv";
        if (load_mask_file(path, p, all)) ++loaded;
    }
    // FilipTupleT3 was added after the first three-family mask run and is
    // stored separately to preserve those already verified files.
    const std::string prefix4 =
        "results/target_22224_a2228_curves_plus3_f4_masks_p";
    for (int p : primes) {
        std::string path = prefix4 + std::to_string(p) + ".tsv";
        load_mask_file(path, p, all);
    }
    const std::string prefix56 =
        "results/target_22224_a2228_curves_plus3_product_masks_p";
    for (int p : primes) {
        std::string path = prefix56 + std::to_string(p) + ".tsv";
        load_mask_file(path, p, all);
    }
    if (!loaded) {
        std::cerr << "No mask files found for prefix " << prefix << "\n";
        return 2;
    }
    std::ofstream out(output);
    out << "family\tnumerator\tdenominator\n";
    std::cerr << "A2228_PLUS3_CRT_START H=" << H << " masks=" << loaded << "\n";
    for (int family = 1; family <= 6; ++family) {
        Searcher s{H, family, all[family - 1], out};
        s.run();
    }
    std::cerr << "A2228_PLUS3_CRT_DONE output=" << output << "\n";
    return 0;
}
