//////////////////////////////////////////////////////////////////////
// Mordell--Weil residue sieve on the seven pair-scaling elliptic fibers.
//
// We follow the known infinite-order point Q on each elliptic quotient,
// retain every rational torsion coset, and intersect the multiplier classes
// for which the associated genus-2 curve has either boundary reduction or
// 3 | #J(F_p).  P1 is the exact rank-one control; for P2--P7 this sieves the
// distinguished infinite-order direction generated by the second bank point.
//////////////////////////////////////////////////////////////////////

SetColumns(0); SetSeed(1);
Q:=Rationals(); Z:=Integers(); PR<p>:=PolynomialRing(Q);

if not assigned FiberStart then FiberStart:=1; end if;
if Type(FiberStart) eq MonStgElt then FiberStart:=StringToInteger(FiberStart); end if;
if not assigned FiberEnd then FiberEnd:=7; end if;
if Type(FiberEnd) eq MonStgElt then FiberEnd:=StringToInteger(FiberEnd); end if;
if not assigned PrimeList then PrimeList:=[11,13,17,19,23,29,31,37,41,43,47,53,59,61];
elif Type(PrimeList) eq MonStgElt then PrimeList:=[StringToInteger(s):s in Split(PrimeList,",")];
end if;
if not assigned MaxN then MaxN:=500; end if;
if Type(MaxN) eq MonStgElt then MaxN:=StringToInteger(MaxN); end if;
if not assigned HeightCeiling then HeightCeiling:=10^120; end if;
if Type(HeightCeiling) eq MonStgElt then HeightCeiling:=StringToInteger(HeightCeiling); end if;
if not assigned MaxClasses then MaxClasses:=200000; end if;
if Type(MaxClasses) eq MonStgElt then MaxClasses:=StringToInteger(MaxClasses); end if;
if not assigned log_file then
    log_file:="results/target_22224_offrectangle_new_curves_pairfiber_mwsieve.log";
end if;
if not assigned output_file then
    output_file:="results/target_22224_offrectangle_new_curves_pairfiber_mwsieve_candidates.tsv";
end if;

SetLogFile(log_file:Overwrite:=true);
out:=Open(output_file,"w");
fprintf out,"fiber\ttorsion_coset\tn\tmodulus\tlambda\theight\ta\tb\tc\td\tboundary_primes\tthree_survivor\tgcd_bound\n";

families := [
 <"P1",[Q!1,Q!55,Q!99,Q!125],Q!1089/25>,
 <"P2",[Q!20,Q!225,Q!304,Q!380],Q!9>,
 <"P3",[Q!13,Q!276,Q!624,Q!828],Q!16>,
 <"P4",[Q!41,Q!256,Q!800,Q!1312],Q!6400/1681>,
 <"P5",[Q!2,Q!46,Q!292,Q!1679],Q!4>,
 <"P6",[Q!18,Q!158,Q!711,Q!1764],Q!6241/1764>,
 <"P7",[Q!50,Q!791,Q!2800,Q!5650],Q!196/25>
];

function ExactSquare(x)
    x:=Q!x; if x lt 0 then return false,Q!0; end if;
    okN,n:=IsSquare(Z!Numerator(x)); if not okN then return false,Q!0; end if;
    okD,d:=IsSquare(Z!Denominator(x)); if not okD then return false,Q!0; end if;
    return true,Q!n/Q!d;
end function;

function PrimitiveTuple(vals)
    den:=LCM([Denominator(Q!z):z in vals]); ints:=[Z!(Q!z*den):z in vals];
    g:=GCD(ints); if g ne 0 then ints:=[z div g:z in ints]; end if;
    return Sort([Abs(z):z in ints]);
end function;

function ThreeBound(vals)
    f:=p*&*[p+z^2:z in vals]; g:=0; used:=[];
    for ell in PrimesUpTo(199) do
        try
            fp:=ChangeRing(f,GF(ell));
            if Degree(fp) ne 5 or Discriminant(fp) eq 0 then continue; end if;
            n:=Z!Evaluate(LPolynomial(HyperellipticCurve(fp)),1);
            g:=(g eq 0) select n else GCD(g,n); Append(~used,<ell,n,g>);
            if g mod 3 ne 0 then return false,g,used; end if;
        catch e continue;
        end try;
    end for;
    return g ne 0 and g mod 3 eq 0,g,used;
end function;

function ReduceRat(q,F)
    q:=Q!q; ell:=Z!Characteristic(F);
    if Denominator(q) mod ell eq 0 then return false,F!0; end if;
    return true,F!Numerator(q)/F!Denominator(q);
end function;

function ReducePoint(PQ,EF)
    if PQ eq Parent(PQ)!0 then return true,EF!0; end if;
    cs:=[Q!PQ[i]:i in [1..3]]; den:=LCM([Denominator(z):z in cs]);
    ints:=[Z!(z*den):z in cs]; g:=GCD(ints); if g ne 0 then ints:=[z div g:z in ints]; end if;
    F:=BaseRing(EF); vals:=[F!z:z in ints];
    if &and[z eq 0:z in vals] then return false,EF!0; end if;
    try return true,EF!vals; catch e return false,EF!0; end try;
end function;

function CRT2(a,m,b,n)
    g,s,t:=XGCD(m,n); delta:=b-a;
    if delta mod g ne 0 then return false,0,0; end if;
    ng:=n div g; k:=((delta div g)*s) mod ng; M:=(m div g)*n;
    return true,(a+m*k) mod M,M;
end function;

function FamilyAllowedLambda(lam,isinf,z,ell)
    if isinf then return true,true,-1; end if;
    F:=GF(ell); R<x>:=PolynomialRing(F);
    vals:=[lam*(F!z[1]),F!z[2],F!z[3],lam*(F!z[4])];
    f:=x*&*[x+q^2:q in vals];
    if Degree(f) ne 5 or Discriminant(f) eq 0 then return true,true,-1; end if;
    n:=Z!Evaluate(LPolynomial(HyperellipticCurve(f)),1);
    return n mod 3 eq 0,false,n;
end function;

function ReduceMapPolys(polys,F)
    out:=[];
    try
        for h in polys do Append(~out,ChangeRing(h,F)); end for;
    catch e
        return false,[];
    end try;
    return true,out;
end function;

function LambdaFromEPoint(PF,mapPolys,F,a,b,c,d,Kp)
    if PF eq Parent(PF)!0 then
        // The chosen identity is the lambda=1 base point.
        return true,false,F!1;
    end if;
    xyz:=[PF[i]:i in [1..3]];
    cv:=[Evaluate(h,xyz):h in mapPolys];
    if #cv ne 3 or &and[z eq 0:z in cv] or cv[3] eq 0 then
        return true,true,F!0;
    end if;
    pp:=cv[1]/cv[3]; den:=(F!d)*pp^2-(F!Kp)*(F!a);
    if den eq 0 then return true,true,F!0; end if;
    lam:=((F!Kp)*(F!c)-(F!b)*pp^2)/den;
    return true,false,lam;
end function;

print "PAIRFIBER_MWSIEVE_START","fibers",FiberStart,FiberEnd,
      "primes",PrimeList,"MaxN",MaxN,"HeightCeiling",HeightCeiling;

for fi in [Max(1,FiberStart)..Min(#families,FiberEnd)] do
    fam:=families[fi]; name:=fam[1]; z:=fam[2]; lam1:=fam[3];
    a,b,c,d:=Explode(z); Kp:=(d+b)/(a+c); Kq:=(a+b)/(d+c);
    Ap:=a*(Kp*c-b*p^2)+b*(d*p^2-Kp*a);
    Bp:=-Kq*d*(Kp*c-b*p^2)-Kq*c*(d*p^2-Kp*a);
    C:=HyperellipticCurve(-Ap*Bp); P0:=C![Q!1,Evaluate(Ap,Q!1),Q!1];
    function Ratios(lam)
        return ((a*lam+b)*(a*lam+c))/((a+b)*(a+c)),
               ((a*lam+b)*(d*lam+b))/((a+b)*(d+b)),
               ((a*lam+c)*(d*lam+c))/((a+c)*(d+c));
    end function;
    Ra,Rb,Rc:=Ratios(lam1); oka,ya:=ExactSquare(Ra); okb,yb:=ExactSquare(Rb); okc,yc:=ExactSquare(Rc);
    assert oka and okb and okc;
    p1:=ya/yb; q1:=yc/ya; P1:=C![p1,q1*Evaluate(Ap,p1),Q!1];
    E,phi:=EllipticCurve(C,P0); Einv:=Inverse(phi); mapPolys:=DefiningPolynomials(Einv);
    Qgen:=phi(P1); assert Order(Qgen) eq 0;
    TG,tmap:=TorsionSubgroup(E); torsGlobal:=[tmap(g):g in TG];
    classes:=[<ti,0,1>:ti in [1..#torsGlobal]]; usedPrimes:=[];
    print "FAMILY_START",name,"torsion",Invariants(TG),"Q",Qgen;

    for ell in PrimeList do
        F:=GF(ell); okE:=true; ainvF:=[];
        for q in aInvariants(E) do okq,v:=ReduceRat(q,F); if not okq then okE:=false; break; end if; Append(~ainvF,v); end for;
        if not okE then print "PRIME_SKIP",name,ell,"E_denominator"; continue; end if;
        try
            EF:=EllipticCurve(ainvF);
        catch e
            print "PRIME_SKIP",name,ell,"E_bad_reduction";
            continue;
        end try;
        okG,Gp:=ReducePoint(Qgen,EF); if not okG then print "PRIME_SKIP",name,ell,"G_reduce"; continue; end if;
        ord:=Order(Gp); if ord eq 0 then print "PRIME_SKIP",name,ell,"G_order"; continue; end if;
        okMap,mapF:=ReduceMapPolys(mapPolys,F); if not okMap then print "PRIME_SKIP",name,ell,"map_denominator"; continue; end if;
        torsF:=[]; okT:=true;
        for TQ in torsGlobal do okt,Tp:=ReducePoint(TQ,EF); if not okt then okT:=false; break; end if; Append(~torsF,Tp); end for;
        if not okT then print "PRIME_SKIP",name,ell,"torsion_reduce"; continue; end if;

        allowedByT:=[]; boundaryByT:=[];
        for ti in [1..#torsF] do
            allowed:=[]; bcount:=0;
            for n in [0..ord-1] do
                ep:=n*Gp+torsF[ti]; okL,isinf,lam:=LambdaFromEPoint(ep,mapF,F,a,b,c,d,Kp);
                if not okL then continue; end if;
                yes,boundary,jord:=FamilyAllowedLambda(lam,isinf,z,ell);
                if yes then Append(~allowed,n); end if;
                if boundary then bcount+:=1; end if;
            end for;
            Append(~allowedByT,allowed); Append(~boundaryByT,bcount);
        end for;

        next:=[]; seenC:={};
        for cls in classes do
            ti:=cls[1];
            for n in allowedByT[ti] do
                okcrt,r,M:=CRT2(cls[2],cls[3],n,ord);
                if okcrt then
                    key:=Sprintf("%o:%o:%o",ti,r,M);
                    if key notin seenC then Include(~seenC,key); Append(~next,<ti,r,M>); end if;
                end if;
            end for;
        end for;
        classes:=next; Append(~usedPrimes,ell);
        print "PRIME_SIEVE",name,"p",ell,"ordQ",ord,
              "allowed",[#s:s in allowedByT],"boundary",boundaryByT,
              "classes",#classes;
        if #classes eq 0 or #classes gt MaxClasses then break; end if;
    end for;

    print "FAMILY_CLASSES",name,"used_primes",usedPrimes,"count",#classes;
    if #classes le 100 then print classes; end if;
    seenExact:={}; exactChecked:=0; fullLifts:=0; heightSkip:=0; threeHits:=0;
    for cls in classes do
        ti,r,M:=Explode(cls);
        for n in [-MaxN..MaxN] do
            if (n-r) mod M ne 0 then continue; end if;
            key:=Sprintf("%o:%o",ti,n); if key in seenExact then continue; end if; Include(~seenExact,key);
            exactChecked+:=1; ep:=n*Qgen+torsGlobal[ti];
            try cp:=Einv(ep); catch e continue; end try;
            if cp[3] eq 0 then continue; end if;
            pp:=Q!(cp[1]/cp[3]); den:=d*pp^2-Kp*a; if den eq 0 then continue; end if;
            lam:=(Kp*c-b*pp^2)/den; RaQ,RbQ,RcQ:=Ratios(lam);
            okLift,sq:=ExactSquare(RaQ); if not okLift then continue; end if;
            ok2,sq2:=ExactSquare(RbQ); ok3,sq3:=ExactSquare(RcQ); if not ok2 or not ok3 then continue; end if;
            vals:=[a*lam,b,c,d*lam]; prim:=PrimitiveTuple(vals); fullLifts+:=1;
            if Maximum(prim) gt HeightCeiling then heightSkip+:=1; continue; end if;
            boundaryPr:=[];
            for ell in usedPrimes do
                F:=GF(ell); okLam,lamF:=ReduceRat(lam,F);
                if not okLam then Append(~boundaryPr,ell); continue; end if;
                yes,bd,jord:=FamilyAllowedLambda(lamF,false,z,ell); if bd then Append(~boundaryPr,ell); end if;
            end for;
            survives,g,used:=ThreeBound(vals); if survives then threeHits+:=1; end if;
            fprintf out,"%o\t%o\t%o\t%o\t%o\t%o\t%o\t%o\t%o\t%o\t%o\t%o\t%o\n",
                    name,ti,n,M,lam,Maximum(prim),prim[1],prim[2],prim[3],prim[4],
                    Sprint(boundaryPr),survives select 1 else 0,g;
            print "EXACT_CLASS",name,"ti",ti,"n",n,"mod",M,
                  "height",Maximum(prim),"boundary",boundaryPr,
                  "three",survives,"gcd",g;
            if survives then
                f:=p*&*[p+q^2:q in vals]; G,jmap:=TorsionSubgroup(Jacobian(HyperellipticCurve(f)));
                print "TARGET_EXACT_TORSION",name,ti,n,prim,Invariants(G);
            end if;
        end for;
    end for;
    print "FAMILY_DONE",name,"classes",#classes,"exact_checked",exactChecked,
          "full_lifts",fullLifts,"height_skip",heightSkip,"three_hits",threeHits;
end for;

delete out;
print "PAIRFIBER_MWSIEVE_DONE";
UnsetLogFile(); quit;
